### ISSUE TITLE
can't share any file/image

### ISSUE THREAD

**Issue by fuzunspm** [nextcloud/spreed-ios#1024]
## Steps to reproduce
1. Upload image/file from device memory or nextcloud app

### Expected behaviour
File should be shared with chat instance

### Actual behaviour
It throws an error of `404: The requested resource could not be found`

## Device information

**Device:**
iPhone 13 Pro

**iOS version:**
16.1.1

**Talk version:**
15.1.1

## Server information

**Nextcloud version:**
25.0.2

**Talk version:**
15.0.2

**Custom Signaling server configured:**
no

**Custom TURN server configured:**
yes

**Custom STUN server configured:**
yes

### Server log (data/nextcloud.log)
no error is outputed for nextcloud or nginx

**Comment by SystemKeeper** [comment]
Hey @fuzunspm, did this work before and only stopped in one of the newer versions ?

**Comment by fuzunspm** [comment]
yes it was working fine since i'm using Talk, like a few years. I think it's stopped after i switched to php 8 because nextcloud was giving warnings about it. After switching i checked all the logs and messages to ensure that it's not missing anything until i found out today i can't share anything on Talk. It's fine on web browser by the way.

**Comment by SystemKeeper** [comment]
Could you add a new test user add check if uploading works for that new user? So we can check if it’s related to the instance or your user

**Comment by fuzunspm** [comment]
sorry, i re-logged in to my account and now it's working. Thank you very much for the hint
