### ISSUE TITLE
The keyboard disappears when going back to the chat view after ending a call

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#1034]
## Steps to reproduce
1. Get video called
2. Answer (maybe this only works when answering from the call screen with the phone unlocked?)
3. Do the call
4. Hang up (I don't know if the other party has to hang up first for this to happen)
5. The chat is there as expected, but it appears like there should be a keyboard showing which is not there (it's just black)

### Expected behaviour
Either the keyboard should be showing and working, or it should be "closed" (meaning that we're not in typing mode).

### Actual behaviour
The keyboard disappears. I think that just going back to the chat list is sufficient to make the app work again, but I can't remember, maybe the app needs to be closed manually from the app switcher.

## Device information

**Device:** iPhone X

**iOS version:** 16.2

**Talk version:** 15.2.3

## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`) 25.0.2

**Talk version:** (see apps admin page: `/index.php/settings/apps`) 15.0.2

**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/settings/admin/talk#signaling_server`) no

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`) yes

**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`) yes

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by e-caste** [comment]
This also happens after sending a picture after selecting Attachments -> Camera/Camera Roll -> choose picture -> Send

Screenshot of the bottom part of the screen:![image](https://user-images.githubusercontent.com/48513706/212718760-9d196cbe-78c4-4d54-a8fa-a952eefc63d7.jpeg)

**Comment by SystemKeeper** [comment]
Thank you @e-caste ! I haven't looked into the call one, but the camera one is easily reproducible. 

Probably makes sense to hide the keyboard after selecting a corresponding option:

https://github.com/nextcloud/talk-ios/blob/8129b045173c1753c92c2f51a317c68e015c3bea/NextcloudTalk/NCChatViewController.m#L1296-L1342

Something like `[self dismissKeyboard:NO];`. Wanna take a look yourself? 😄

**Comment by e-caste** [comment]
Hey @SystemKeeper thanks for replying. Sorry, but I'm quite busy at the moment, I hope to be able to contribute again in the future though! In the meantime, I'll keep opening issues if I find any!

**Comment by SystemKeeper** [comment]
Sure, happy to see you again any time 😄

**Comment by SystemKeeper** [comment]
I was wrong here @e-caste. This (both cases) were actually introduced accidentally and fixed in #1041. Thanks again for the report!
