### ISSUE TITLE
Not working with self signed certificate on iOS

### ISSUE THREAD

**Issue by CipherChen** [nextcloud/spreed-ios#1070]
Yes I've already search everything about Talk not working with self-signed certificate server, and I know some workaround, but not suitable for me. Some points:

1. iPhone 14 (iPhone 11 had been tried and not work)
2. iOS16.2 (earlier version had been tried and not work)
3. My certificates (root ca/crt) are signed by myself
4. Maybe Let's Encrypt can work, but my certificate has multiple usage and not allowed to switch to Let's Encrypt
5. Self-signed certificate Ca/crt files have been imported into iOS Configuration Description Files
6. Nextcloud works perfectly with this server on this device, but
7. When Talk "Import Account" From Nextcloud, Talk acts like pic1: circling and nothing happened.
8. When input server address manually, Talk acts like pic2: "Nextcloud server not found, ssl error happened, can not connect with server securely. Please confirm if you input correct nextcloud server address."

pic1:
![f8a705012d279d11792a05ad29f5361](https://user-images.githubusercontent.com/3151289/217171111-2445549c-50a9-4ad5-aac9-6d6e1084d1ba.jpg)

pic2:
![35b2a310c7fa72f373b07ab673afa99](https://user-images.githubusercontent.com/3151289/217171121-1df1d61f-ade1-41cc-908d-239666c493fd.jpg)

**Comment by SystemKeeper** [comment]
Hey, please make sure your certificate fullfills ATS requirements: https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW57

**Comment by CipherChen** [comment]
Hi @SystemKeeper

**Comment by CipherChen** [comment]
Hi, all tls test are passed using 'nscurl --ats-diagnostics'.

**Comment by SystemKeeper** [comment]
Hm, can you post the output of `nscurl --ats-diagnostics --verbose`? (Replace the url before posting)

**Comment by CipherChen** [comment]
Domain has been replaced with fake.domain.com.

```
» nscurl --ats-diagnostics https://fake.domain.com:8443 --verbose
Starting ATS Diagnostics

Configuring ATS Info.plist keys and displaying the result of HTTPS loads to https://fake.domain.com:8443.
A test will "PASS" if URLSession:task:didCompleteWithError: returns a nil error.
================================================================================

Default ATS Secure Connection
---
ATS Default Connection
ATS Dictionary:
{
}
Result : PASS
---

================================================================================

Allowing Arbitrary Loads

---
Allow All Loads
ATS Dictionary:
{
    NSAllowsArbitraryLoads = true;
}
Result : PASS
---

================================================================================

Configuring TLS exceptions for fake.domain.com

---
TLSv1.3
ATS Dictionary:
{
    NSExceptionDomains =     {
        "fake.domain.com" =         {
            NSExceptionMinimumTLSVersion = "TLSv1.3";
        };
    };
}
Result : PASS
---

---
TLSv1.2
ATS Dictionary:
{
    NSExceptionDomains =     {
        "fake.domain.com" =         {
            NSExceptionMinimumTLSVersion = "TLSv1.2";
        };
    };
}
Result : PASS
---

---
TLSv1.1
ATS Dictionary:
{
    NSExceptionDomains =     {
        "fake.domain.com" =         {
            NSExceptionMinimumTLSVersion = "TLSv1.1";
        };
    };
}
Result : PASS
---

---
TLSv1.0
ATS Dictionary:
{
    NSExceptionDomains =     {
        "fake.domain.com" =         {
            NSExceptionMinimumTLSVersion = "TLSv1.0";
        };
    };
}
Result : PASS
---

================================================================================

Configuring PFS exceptions for fake.domain.com

---
Disabling Perfect Forward Secrecy
ATS Dictionary:
{
    NSExceptionDomains =     {
        "fake.domain.com" =         {
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

================================================================================

Configuring PFS exceptions and allowing insecure HTTP for fake.domain.com

---
Disabling Perfect Forward Secrecy and Allowing Insecure HTTP
ATS Dictionary:
{
    NSExceptionDomains =     {
        "fake.domain.com" =         {
            NSExceptionAllowsInsecureHTTPLoads = true;
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

================================================================================

Configuring TLS exceptions with PFS disabled for fake.domain.com

---
TLSv1.3 with PFS disabled
ATS Dictionary:
{
    NSExceptionDomains =     {
        "fake.domain.com" =         {
            NSExceptionMinimumTLSVersion = "TLSv1.3";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

---
TLSv1.2 with PFS disabled
ATS Dictionary:
{
    NSExceptionDomains =     {
        "fake.domain.com" =         {
            NSExceptionMinimumTLSVersion = "TLSv1.2";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

---
TLSv1.1 with PFS disabled
ATS Dictionary:
{
    NSExceptionDomains =     {
        "fake.domain.com" =         {
            NSExceptionMinimumTLSVersion = "TLSv1.1";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

---
TLSv1.0 with PFS disabled
ATS Dictionary:
{
    NSExceptionDomains =     {
        "fake.domain.com" =         {
            NSExceptionMinimumTLSVersion = "TLSv1.0";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

================================================================================

Configuring TLS exceptions with PFS disabled and insecure HTTP allowed for fake.domain.com

---
TLSv1.3 with PFS disabled and insecure HTTP allowed
ATS Dictionary:
{
    NSExceptionDomains =     {
        "fake.domain.com" =         {
            NSExceptionAllowsInsecureHTTPLoads = true;
            NSExceptionMinimumTLSVersion = "TLSv1.3";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

---
TLSv1.2 with PFS disabled and insecure HTTP allowed
ATS Dictionary:
{
    NSExceptionDomains =     {
        "fake.domain.com" =         {
            NSExceptionAllowsInsecureHTTPLoads = true;
            NSExceptionMinimumTLSVersion = "TLSv1.2";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

---
TLSv1.1 with PFS disabled and insecure HTTP allowed
ATS Dictionary:
{
    NSExceptionDomains =     {
        "fake.domain.com" =         {
            NSExceptionAllowsInsecureHTTPLoads = true;
            NSExceptionMinimumTLSVersion = "TLSv1.1";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

---
TLSv1.0 with PFS disabled and insecure HTTP allowed
ATS Dictionary:
{
    NSExceptionDomains =     {
        "fake.domain.com" =         {
            NSExceptionAllowsInsecureHTTPLoads = true;
            NSExceptionMinimumTLSVersion = "TLSv1.0";
            NSExceptionRequiresForwardSecrecy = false;
        };
    };
}
Result : PASS
---

================================================================================
```

**Comment by SystemKeeper** [comment]
Thank you for the details! Honestly I don’t know right now… would it be possible to get the URL you’re trying to connect to? You can find my mail in the header of this file https://github.com/nextcloud/talk-ios/blob/c44696d96f2bc49da956cb8daf9cef955f774dc4/NextcloudTalk/CallsFromOldAccountViewController.swift

**Comment by CipherChen** [comment]
Hi @SystemKeeper , email sent. Thanks.

**Comment by SystemKeeper** [comment]
> Hi @SystemKeeper , email sent. Thanks.

Hey, thank you! You said that you added the certificate to the device. Did you add the corresponding CA to the device and set it to trusted, like here https://support.apple.com/en-us/HT204477 ?
It could still be an ATS issue after all, because the trust in the system is missing:
```
2023-02-09 12:14:15.107654+0100 NextcloudTalk[15548:9715584] ATS failed system trust
2023-02-09 12:14:15.107738+0100 NextcloudTalk[15548:9715584] Connection 5: system TLS Trust evaluation failed(-9802)
```
(On the files app it could be that (because ATS is not enforced) you get a warning, but can continue)

**Comment by CipherChen** [comment]
Hi, I self-signed a root ca (CN=”DOMAIN") and a domain  ca (CN="fake.domain.com").

root crt and domain crt are all trusted on the device:

VPN & Device Management:

![6cbab04409bf001680d29d8f62f6d66](https://user-images.githubusercontent.com/3151289/217974924-374dc5c8-dbcd-43e3-9ae2-de487a0c4430.jpg)

Certificate Trust Settings:

![6fb5a71c9d43eb7e35cfde5b88d3e9a](https://user-images.githubusercontent.com/3151289/217974960-2723660a-83d5-42ea-9fc2-99fa26cb25f6.jpg)

**Comment by CipherChen** [comment]
Hi @SystemKeeper I pretty sure that the problem is self-signed certificate, I've already switched to Let's Encrypted, and Talk works now on iOS.
Really appreciate for you help.

And still hope self-signed certificate can be fully supported.

**Comment by SystemKeeper** [comment]
Hey @CipherChen 
sorry I forgot to reply to you yesterday. I did some tests and couldn't make it work with your certificate. One thing I noticed that the certificate provides does not include the full chain, that is including the CA Cert. Maybe you could give this a try? 
Also I was not able to connect with the files app as well. (I could not test with the CA trusted, because the CA Cert was not included)

In any way, using lets encrypt (or any other officially trusted CA) is a good solution 👍

**Comment by SystemKeeper** [comment]
I'll close this for now as from the talk-ios side everything works as expected.
