### ISSUE TITLE
Allow continuous recording of voice messages

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed-ios#1088]
Meta ticket at https://github.com/nextcloud/spreed/issues/8819

(I checked Android, but I guess it's similar for iOS)
> I checked Telegram, Signal and Whatsapp and they all have a "slide top to lock in" option.

Maybe we can also add something a like.

**Comment by SystemKeeper** [comment]
See https://github.com/nextcloud/talk-ios/issues/886
The request was there already from time to time. Also seen this on a App Store review.

**Comment by nickvergessen** [comment]
Ah okay, closing as duplicate then
