### ISSUE TITLE
iPad view left sidebar does not "cheat" unread counter anymore

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed-ios#1123]
## Steps to reproduce
1. Have multiple chats Chat 1-3 with unread messages
2. Go into Chat 1 and read everything, unread counter is still shown
3. Jump to Chat 2 and read everything, unread counter for Chat 1+2 is still shown

### Expected behaviour
After reading the chat the unread counter should be removed (set to 0)
I think this is a regression as I'm pretty sure it worked before.

### Actual behaviour
After "random" 30 sec refreshing the counter disappears.

## Device information

**Talk version:** Testflight

## Server information

**Nextcloud version:** 26rc2 c-nc-c

**Talk version:** 16rc3

**Comment by SystemKeeper** [comment]
But this did work correctly before?

**Comment by nickvergessen** [comment]
Thanks for the speedy fix 👍
