### ISSUE TITLE
Answering to a video call from the lock screen works, but doesn't show own video

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#1162]
## Steps to reproduce
1. Receive a video call
2. Tap the blue button to accept it (Talk opens in the video call)
3. Enable video -> the other party sees the video and the video preview appears, but it's transparent so you can't see your own video

### Expected behaviour
Video preview works.

### Actual behaviour
See above.

## Device information

**Device:** iPhone X

**iOS version:** 16.3.1

**Talk version:** 16.0.0

## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`) 26.0.0

**Talk version:** (see apps admin page: `/index.php/settings/apps`) 16.0.0

**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/settings/admin/talk#signaling_server`) no

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`) yes

**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`) yes

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by SystemKeeper** [comment]
Could you post a screenshot of what it looks like for you?!

**Comment by e-caste** [comment]
@SystemKeeper sure. I could reproduce it:
![image](https://user-images.githubusercontent.com/48513706/227708350-af667b27-dcff-484c-974a-3678f1e8e9bb.png)
You can see the transparent video preview at the top, on my other device I can see my face so the stream is working.

**Comment by SystemKeeper** [comment]
Thank you! Does something change when you enter/leave the chat while in this state?

Obviously that should not happen..

**Comment by e-caste** [comment]
@SystemKeeper I have tried:
- tapping the chat button, then closing the chat to go back to the call
- disabling and re-enabling the video
None of these work, sorry

**Comment by SystemKeeper** [comment]
Thanks for trying, we will take a look!

**Comment by e-caste** [comment]
It also looks like it doesn't matter if the phone is locked actually. It happens both if you have it unlocked and tap on the notification and if the phone is locked and you swipe to answer (then tap the "Open in Talk" button).

**Comment by SystemKeeper** [comment]
After around 20 calls I have seen this now as well, funny that it never occurred in our tests. We'll take a look there

**Comment by e-caste** [comment]
Could be a race condition which shows up more easily on my dated iPhone X, you could try older devices to test for this

**Comment by SystemKeeper** [comment]
Yea, I guess it's a timing issue. When the issue occurred the chat view was a bit longer visible before switching to the call view. So I guess we can solve this :-)
