### ISSUE TITLE
Chat view does not update with new messages

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#1176]
## Steps to reproduce
1. Be in a chat
2. Either lock the phone or move to another app
3. Receive a new message in that chat
4. Open Talk

### Expected behaviour
The chat updates with the new message(s) while looking at it.

### Actual behaviour
The chat does not update: the messages are received and the notifications can be seen, but to see the new messages in the chat I have to go back to the chat list and then tap on the chat where I have received them (I can see the last message's preview in the chat preview).

Also, may be related: if I send a new message in this state (that is, I have received the messages but I can't see them in the chat view), then the chat updates with my message first and the received messages after, without respecting the chronological order (see screenshot).
![image](https://user-images.githubusercontent.com/48513706/229242457-70c1af48-6d12-44a1-ae43-3efa2e09a454.jpeg)

## Device information

**Device:** iPhone X

**iOS version:** 16.4

**Talk version:** 16.0.0

## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`) 26.0.0

**Talk version:** (see apps admin page: `/index.php/settings/apps`) 16.0.2

**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/settings/admin/talk#signaling_server`) no

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`) yes

**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`) yes

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by SystemKeeper** [comment]
Hey, was able to reproduce this. We will take a look, thank you for the report!
