### ISSUE TITLE
Ringing status when initiating a call

### ISSUE THREAD

**Issue by y0grt** [nextcloud/spreed-ios#1205]
**Is your feature request related to a problem? Please describe.**
Using the android app, when I initiate a call, in the other end was reached, I see the text 'Ringing', informing me that the other end (a phone, mainly) was notified for this call.
Currently in the iOS app I see 'Waiting for John Doe to join call ...'

**Describe the solution you'd like**
Show 'Ringing' status if the other end was reached

**Describe alternatives you've considered**
An option to disable this to do not notify the other end maybe?

**Additional context**
This happend with and without signaling server

**Comment by SystemKeeper** [comment]
Hey @jmlgo, thanks for bringing this up. Actually I think that this is just a different label for the same thing. So when a call is made a push notification is send through Apples/Googles push notification service. There's no way for us detect if this push notification actually reached the device and distinguish between a "started call" and a "ringing call". Especially in group conversation this wouldn't work at all.

**Comment by y0grt** [comment]
I'll make another test, but IIRC when there is no other end (phone off, no browser tab open) it never shows 'Ringing'.

**Comment by SystemKeeper** [comment]
Hey @jmlgo I'll close this for now. If there's anything to add, feel free to reach out.

**Comment by y0grt** [comment]
Just checked with v16.0.1 on Android. It switch instantly from calling to ringing at any case, at least with the signaling server configured. Thank you for you help.
