### ISSUE TITLE
Reactions menu opens text keyboard

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#1253]
## Steps to reproduce
1. Long press on a message
2. Tap "Add reaction"
3. Keyboard opens

https://github.com/nextcloud/talk-ios/assets/48513706/9aa00ae7-d768-4cfb-96ca-29f6f5eefdc5

### Expected behaviour
The keyboard opens on the emoji tab (this used to happen in past versions) / custom reaction panel opens.

### Actual behaviour
The keyboard opens on the default language tab.

## Device information

**Device:** iPhone X

**iOS version:** 16.5

**Talk version:** 16.0.2

## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`) 26.0.1

**Talk version:** (see apps admin page: `/index.php/settings/apps`) 16.0.4

**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/settings/admin/talk#signaling_server`) no

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`) yes

**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`) yes

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by SystemKeeper** [comment]
Can you please check that you have enabled the emoji keyboard in the iOS settings?

**Comment by e-caste** [comment]
Yes, I have two languages, then the emoji keyboard, then another language. Could it be that you choose the keyboard based on its index? In my case, the keyboard that opens is the second one in the list under Settings > General > Keyboards.  
EDIT: but if I remember correctly, when the emoji keyboard was the last in the order it worked, I'm not sure exactly though, just a thought

**Comment by SystemKeeper** [comment]
No it’s not indexed, we just set the preferred „language“ to be the emoji one. So when no emoji keyboard is available, the default one is shown… I just tried the order you have and it’s working for me. Hm. Could you try to force close talk ios and see if that works? If not, could you try rebooting your phone please ?

**Comment by e-caste** [comment]
Sure, it's been happening for a few days or weeks but let me see:
- force closing and reopening doesn't have any effect
- rebooting doesn't have any effect

**Comment by SystemKeeper** [comment]
Is the emoji keyboard shown when you try to change your user status and select a custom emoji there ?

otherwise I need to think about that, not a good idea right now 😅

**Comment by e-caste** [comment]
I get the default (language) keyboard both if I tap on the smiling emoji at the top left and on the text field at the top right.
![IMG_0376](https://github.com/nextcloud/talk-ios/assets/48513706/63721995-6b9e-4a03-a20a-8d139a615891)

Just to be clear, if I then tap on the emoji keyboard button, I am able to add an emoji reaction to a message, so it's not missing the functionality, it's just that the emoji keyboard doesn't pop up automatically.

**Comment by SystemKeeper** [comment]
I am wondering if something in 16.5 changed. Do you remember if this stopped working after upgrading iOS?

**Comment by e-caste** [comment]
I am pretty sure it was already there in 16.4 / 16.4.1 /  16.4.1 (a), but I couldn't pinpoint the exact update version after which this started happening.

**Comment by SystemKeeper** [comment]
I am on 16.4.1 Right now and it’s working correctly. Let me upgrade to 16.5 just to be sure we are not looking for something that’s not there

**Comment by SystemKeeper** [comment]
Nope, working fine on 16.5 as well

**Comment by SystemKeeper** [comment]
I am running out of ideas right now, sorry. If you still have access to Xcode, you could try to create a new app and just run

```
        for mode in UITextInputMode.activeInputModes {
            print(mode.primaryLanguage)
        }
```

and take a look at the output. There should be an entry for "emoji". But even if it's missing, I don't know why it should be missing.

**Comment by SystemKeeper** [comment]
Closing this now as it is not reproducible on any of our devices.
