### ISSUE TITLE
Make list of open conversations discoverable and usable

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed-ios#1262]
* Overview issue: https://github.com/nextcloud/spreed/issues/6431
* Design idea at https://github.com/nextcloud/spreed/issues/6431#issuecomment-1573232581
    * If that does not work for your client, please reach out to the design team soon, so they can schedule it
* API endpoint at https://nextcloud-talk.readthedocs.io/en/latest/conversation/#get-open-conversations

**Comment by SystemKeeper** [comment]
> * If that does not work for your client, please reach out to the design team soon, so they can schedule it

Currently when pressing the "+" on the conversation list you get this:
<img width=350 src="https://github.com/nextcloud/talk-ios/assets/1580193/c60deb77-ee92-4761-bcb2-b6f257d0fb09"></img>

Would adding a third option at the top `Join open conversation` work for mobile clients? @nextcloud/designers 
CC @mahibi: Not sure if it is like this on android as well?

**Comment by nickvergessen** [comment]
It is:
![photo_2023-06-02_10-18-44](https://github.com/nextcloud/talk-ios/assets/213943/d58ca320-bcd3-444a-8538-3959f6ca4386)
