### ISSUE TITLE
delete button for message of other participant is shown

### ISSUE THREAD

**Issue by mahibi** [nextcloud/spreed-ios#1288]
## Steps to reproduce
tested for photo: long click message & delete message of other participant

### Expected behaviour
delete option is hidden

### Actual behaviour
error message is shown

## Device information
**Talk version:** 17.0.0

## Server information
sermo

**Talk version:** 28.0.0 dev

**Comment by SystemKeeper** [comment]
Hm, only for yourself and moderators:
https://github.com/nextcloud/talk-ios/blob/a68d3900411dcfcfec9cce526613014fbf318c48/NextcloudTalk/NCChatMessage.m#L278

You sure you're not a moderator in this szenario?

**Comment by mahibi** [comment]
it was in a 1:1 chat

**Comment by SystemKeeper** [comment]
Right... Hm, maybe we should not check the owner here. @Ivansss Can we just remove the owner check? Moderator should be enough in that case along with the check for the same user?
