### ISSUE TITLE
Connection loss answering call in phone standby

### ISSUE THREAD

**Issue by Ho551** [nextcloud/spreed-ios#1319]
## Steps to reproduce
1. Get a call with phone on standby
2. answering the call 
3. First seconds without problems
4. Connection is loss 

### Expected behaviour
Answering a call without any connection loss

### Actual behaviour
Connection loss answering call in phone standby

## Device information

**Device:** iPhone 12

**iOS version:** 16.6

**Talk version:**  17.0.0

## Server information

**Nextcloud version:** 27.0.1
**Talk version:** 17.0.3

**Custom Signaling server configured:** yes and version 1.1.2

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes
### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by SystemKeeper** [comment]
> 3\. First seconds without problems
> 4\. Connection is loss

I am wondering, could it be that after a few seconds your phone connects to Wi-Fi?

**Comment by TBI-NS** [comment]
> > 3. First seconds without problems
> > 4. Connection is loss
> 
> I am wondering, could it be that after a few seconds your phone connects to Wi-Fi?

Hello,

I've encountered the same issue a few times before (my server is at my home, so I had to switch from WiFi to 4G in order to get out of my own network).

For some time now, if I answer a call with the iPhone locked (lock screen), the call doesn't start. I then have to unlock it, and the call starts working properly.

**Comment by SystemKeeper** [comment]
> For some time now, if I answer a call with the iPhone locked (lock screen), the call doesn't start. I then have to unlock it, and the call starts working properly.

That might actually be something different, as apple changed the way how calls are handled when the phone is locked. See https://github.com/nextcloud/talk-ios/issues/903 for details.

**Comment by Ho551** [comment]
Had the problem again now.
In order to participate in a call, I had to terminate the WiFi connection. Afterwards I was able to take part in the call.
It didn't matter whether the call was joined from standby or directly in the app.
The WLAN connection itself cannot be a problem; it was possible to participate easily via a laptop.
It seemed like the iPhone was switching between WiFi and LTE all the time.
iOS 17.1.1 is currently installed

**Comment by Ho551** [comment]
Yesterday I had the problem again. A call was made and the connection was active for both participants for a few seconds. After a few seconds, one participant (A) got a "reconnecting" animation and the other call participant (B) could no longer be heard. However, the connection was still active because participant (B) could still hear participant (A). Participant (A) was then permanently stuck in the reconnecting loop.
So far, the problem has only occurred with participants who were being called.

iOS 17.5.1
iOS Talk 19.0.7

**Comment by SystemKeeper** [comment]
Hm, it still feels like an network issue, although it is weird, that the connection was still established one-way.
Would it be possible to get the debug log of both phones? You can find them in the iOS files app (the iOS native one), under Nextcloud Talk -> logs. You can find my mail address in the header of this file: https://github.com/nextcloud/talk-ios/blob/stable18/NextcloudTalk/VLCKitVideoViewController.swift.
Also the HPB logs in the given timeframe would be interesting, if you're willing/able to share them.

**Comment by SystemKeeper** [comment]
We fixed several reconnection issues with the upcoming talk ios 20 release - from the current data I would assume that this also fixes the issues described here. Feel free to test the TestFlight version: https://github.com/nextcloud/talk-ios?tab=readme-ov-file#testflight
I'll close the issue for now, if you see it with 20 as well, feel free to re-open!
