### ISSUE TITLE
Support "File caption"

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed-ios#1346]
- Overview at https://github.com/nextcloud/spreed/issues/5354

---

- [ ] Allowing sending a caption
- [ ] Render captioned attachements
- [ ] ~~Support multiple media files in a single message~~

Fix https://github.com/nextcloud/talk-ios/issues/779

**Comment by nickvergessen** [comment]
In case you are tracking the wrong branches (after we split multiple-files from captions), API and server frontend are in ✅

**Comment by SystemKeeper** [comment]
Last bullet point (rendering of multiple images) will be scratched for now, right @nickvergessen ?

**Comment by nickvergessen** [comment]
yes, moved to a follow up idea
