### ISSUE TITLE
Push notification does not work

### ISSUE THREAD

**Issue by davidpr78** [nextcloud/spreed-ios#1347]
New messages are not being pushed, even if iPhone-Settings say yes.

### Expected behaviour
Get a push notification

### Actual behaviour
There comes no push notification

## Device information

**Device:** iPhone X and higer

**iOS version:** 16.6

**Talk version:** 17

(It works with the andriod app on the same server)

**Comment by SystemKeeper** [comment]
Please check https://github.com/nextcloud/talk-ios/blob/master/docs/notifications.md
there are currently no known issues from the app itself. The `occ` test command should be a good start. 
Also can you please check in the App under Diagnostics when the last push subscription was?

**Comment by davidpr78** [comment]
Ok thanks (today 6 of my colleagues complained)

**Comment by SystemKeeper** [comment]
Hm, sounds like it worked correctly before. I would suggest to check the nextcloud.log if anything was logged. Also issuing the occ test command could give you a hint if something is wrong.
