### ISSUE TITLE
Latest update (17.1.0) crashes when opening a conversation

### ISSUE THREAD

**Issue by r-vdz** [nextcloud/spreed-ios#1365]
## Steps to reproduce
1. Open Nextcloud Talk on iOS
2. Select a conversation to view

### Expected behaviour
Tell us what should happen

The app should open the conversation without crashing.

### Actual behaviour
Tell us what happens instead

The application crashes to iOS home screen.

## Device information

**Device:** iPhone 14 Pro, iPad Air 5th gen, and more

**iOS version:** 16.6.1 & 17.0

**Talk version:** 17.1.0

## Server information

**Nextcloud version:** 23.0.12

**Talk version:** 13.0.11

**Custom Signaling server configured:** No

**Custom TURN server configured:** No

**Custom STUN server configured:** No

### Server log (data/nextcloud.log)
<details>
No pertinent server logs related to Talk
</details>

The only other thing I found was in iOS analytics data (Privacy & Security -> Analytics & Improvements -> Analytics Data) there are logs for the app, and in one labelled 'NextcloudTalk-2023-09-19-203030.ips' there is some words like 'exception' and 'EXC_CRASH' and 'SIGABRT' and 'termination' - etc.

**Comment by SystemKeeper** [comment]
Thanks for the report! I was able to reproduce this, we‘ll take a look.
Please note that your nextcloud version is not supported anymore, you should look into upgrading.

**Comment by r-vdz** [comment]
Thank you so much!

And I know I need to upgrade, there are a host of dependencies up through the OS version that means a dist upgrade and I've been lazy. :)

**Comment by SystemKeeper** [comment]
17.1.1 as been released this morning

**Comment by r-vdz** [comment]
Got, and the fix worked! Thanks so much!
