### ISSUE TITLE
Add "Format" options when selecting text

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#1374]
**Is your feature request related to a problem? Please describe.**
Now that Talk supports Markdown formatting (🔥🔥), it would be great to not have to remember the Markdown syntax.

**Describe the solution you'd like**
How Talk is currently doing it:
![image](https://github.com/nextcloud/talk-ios/assets/48513706/a7972d60-a80d-4811-8305-145b27792a2e)

It would be nice to have a Format option when you select some text, which would add the characters around it to format it in Markdown (e.g. underscores for italic, double underscores for bold).

How Telegram and Whatsapp do it:
![image](https://github.com/nextcloud/talk-ios/assets/48513706/1fc6a228-9463-4b06-8598-ecc7a1632f69)
![image](https://github.com/nextcloud/talk-ios/assets/48513706/f6b97616-76dd-4b34-aa55-a261b4347cee)

How GitHub does it:
![image](https://github.com/nextcloud/talk-ios/assets/48513706/f1555017-3774-49c2-aef6-1ad5f6971564)

**Bonus**: since formatting is done with Markdown, it requires adding special characters to the text of the message, which remains pure text. It would be great to have a preview of the formatted text in the composer view, with the added characters like ChatGPT or without like Telegram and Whatsapp.

**Describe alternatives you've considered**
`Remembering` ~~the~~ _Markdown_ **syntax**.

**Additional context**
Great job adding the text formatting feature!

**Comment by SystemKeeper** [comment]
- See: https://github.com/nextcloud/talk-ios/pull/1315 
;-)

**Comment by SystemKeeper** [comment]
Done in https://github.com/nextcloud/talk-ios/pull/1315
