### ISSUE TITLE
No new messages after clearing all messages

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed-ios#1388]
## Steps to reproduce
1. Go to room info
2. Clear all messages

### Expected behaviour
After returning to the chat, we should see the system message "You cleared all messages"

### Actual behaviour
The ViewController is just empty. (works fine after re-entering the room).

**Comment by Ivansss** [comment]
Also Inputbar buttons are disabled when coming back from the RoomInfoViewController 🤔

**Comment by SystemKeeper** [comment]
Did you test with the PR? https://github.com/nextcloud/talk-ios/pull/1389
That is working fine for me 🤔
