### ISSUE TITLE
Extremely slow on iOS 16.3

### ISSUE THREAD

**Issue by moritztim** [nextcloud/spreed-ios#1415]
## Steps to reproduce
1. Use the app normally

### Expected behaviour
nothing special

### Actual behaviour
It feels like the app is working on one thread. Everything is blocking. I can only continue typing, for example, when the voice message I recieved has finished downloading. Nothing happens concurrently it's always one after another. Specifically while typing my key presses get queued up and once any other tasks are finished they are entered all at once.
This has nothing to do with the speed of the internet connection or switching networks.

## Device information

**Device:** iPhone X 

**iOS version:** 16.3

**Talk version:** 17.11

## Server information
n/a, this doesn't happen on my other devices with newer iOS versions.

### Server log (data/nextcloud.log)
n/a

**Comment by SystemKeeper** [comment]
Thanks for your report! Currently we are not aware of any issue that would cause the behaviour you're seeing. As a quick idea, can you check that the IP of your phone is not bruteforce protected by the nextcloud instance?

```
occ security:bruteforce:attempts 123.123.123.123
```

**Comment by moritztim** [comment]
Sure. What's OCC? I can't find any such packages or preinstalled commands on arch

**Comment by moritztim** [comment]
btw this happens in the LAN aswell as in the mobile network

**Comment by SystemKeeper** [comment]
See https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html

**Comment by SystemKeeper** [comment]
You could also try to add a new user to your instance and add it to the phone and try again. This way we could rule out if it’s dependant to your user.

**Comment by moritztim** [comment]
It's probably more likely to be tied to my user. We'll try that soon.

**Comment by SystemKeeper** [comment]
> It's probably more likely to be tied to my user. We'll try that soon.

Thanks, would be really interesting to know what's causing this.

**Comment by moritztim** [comment]
I have tried using a different account but I wasn't able to reproduce it with either this time. Even when unplugged and in power saving mode.

I do want to reiterate that the app basically freezes while sending and recieving messages or loading images or simmilar, which very much points to a client side issue. It's not that the server is rate limiting me, it's that the app itself is running slow.

**Comment by SystemKeeper** [comment]
> I have tried using a different account but I wasn't able to reproduce it with either this time.

Just to be crystal clear here, you can't reproduce this with _any_ account right now or only with _one_ account?

Also, is it with _every_ conversation or just _some_ conversations?

**Comment by moritztim** [comment]
I couldn't reproduce it at all anymore, it doesn't always happen. It did seem to be a bit slower in one particular convo, but there weren't many files or anything like that there, it was like a week or 2 old convo.

**Comment by SystemKeeper** [comment]
I'll close this for now, as there's no reproduction possible. Feel free to reopen when it's reproducible
