### ISSUE TITLE
Can't see who voted after closing poll

### ISSUE THREAD

**Issue by moritztim** [nextcloud/spreed-ios#1416]
## Steps to reproduce
1. Open poll
2. Vote
3. Close poll

### Expected behaviour
On other devices, notably with newer iOS versions, I can see who voted and expect the same from mine.

### Actual behaviour
However I only see percentages.

## Device information

**Device:** iPhone X

**iOS version:** 16.3

**Talk version:** 17.11

## Server information
n/a
### Server log (data/nextcloud.log)
n/a

**Comment by SystemKeeper** [comment]
Hey, thanks for the report, can you post a screenshot on what you see vs what you see on newer iOS versions?

**Comment by moritztim** [comment]
nvm I just now realised that you have to click on the relevant option to see who voted. In the android app you see it directly and someone else with iOS said they see and I just assumed they saw it directly aswell.
