### ISSUE TITLE
NC crash after update 17.1.2

### ISSUE THREAD

**Issue by ghost** [nextcloud/spreed-ios#1428]
## Steps to reproduce
Since the Nextcloud Talk update on November 21, 2023, the app has been crashing on startup.
1. Install Nextcloud from the App Store
2. Connect to the server, log in
3. Open the app and it crashes

### Expected behaviour
The app should display the conversations

### Actual behaviour
It crashes

## Device information

**Device:** iPhone 15 Pro

**iOS version:** 17.1.1

**Talk version:** 17.1.2

## Server information

**Nextcloud version:** 27.1.2

**Talk version:** In/a

I am not the server admin

**Custom Signaling server configured:** n/a

**Custom TURN server configured:** n/a

**Custom STUN server configured:** n/a

### Server log (data/nextcloud.log)
<details>
n/a
Insert your server log here
n/a
</details>

**Comment by SystemKeeper** [comment]
Hey, can you please check if you have a crash report on your phone? It should be in the settings, privacy, analytics and should be named „NextcloudTalk-(…).ips“.
You can send it to the mail found in this file: https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/ChatViewController.swift

**Comment by ghost** [comment]
Hi,i hope this is the right way. I start NC Talk and it closes immediately = for me it‘s a Crash. My Report is attached.Best regardsKatja GraichenAm 23.11.2023 um 12:03 schrieb Marcel Müller ***@***.***>:﻿
Hey, can you please check if you have a crash report on your phone? It should be in the settings, privacy, analytics and should be named „NextcloudTalk-(…).ips“.
You can send it to the mail found in this file: https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/ChatViewController.swift

**Comment by SystemKeeper** [comment]
Thanks, got it, we will check!

**Comment by ghost** [comment]
ThanksI dont know but Version 17.1.1 on my Company Phone (iPhone 15 pro IOS 17.2 Beta 3) work fine. Mit freundlichen GrüßenKatja GraichenAm 23.11.2023 um 12:47 schrieb Marcel Müller ***@***.***>:﻿
Thanks, got it, we will check!

**Comment by Omaha2002** [comment]
Same crash here with IOS 17.1.1, Nextcloud Talk app opens ok, entering correct URL and being redirected to login page of  Nextcloud server, filling in credentials username/password the app crashes after hitting enter.

IOS 17.1.1
Talk app 17.1.2
Nextcloud AIO v7.7.0

Talk works fine through browser on PC en laptop, windows and MacOS.

**Comment by SystemKeeper** [comment]
Thanks for the reports. We found an issue which occurs on iOS 17 devices only. We are preparing a new release. Sorry for the troubles.

**Comment by ptmix** [comment]
Same issue here.... worked after upgrading server from 27.1.3 to 27.1.4, but after the upgrade last night i got back the issue where notifications for a message said something about "message encrypted". I could then still click it and the message form the user opened as expected. But this "encrypted message" notification then did not show that users avatar.

I logget out (and removed app and reinstalled on my iphone), but after adding account and granting access it crashes _instantly_. Impossible to get back in. IOS version is 17.1.1 (latest). I also tried to create a APP Password and scan QR code..... bang, crashes :(

On my IPAD however it works perfectly. IOS 17.1 (latest).

**Comment by SystemKeeper** [comment]
17.1.3 is available in the App Store, please update and check if everything is working fine 🙂

**Comment by ghost** [comment]
Thank youMit freundlichen GrüßenKatja GraichenAm 24.11.2023 um 19:25 schrieb Marcel Müller ***@***.***>:﻿
17.1.3 is available in the App Store, please update and check if everything is working fine 🙂

**Comment by ptmix** [comment]
Working fine here :)
