### ISSUE TITLE
App crashes immediately after start

### ISSUE THREAD

**Issue by cjonas-aapp** [nextcloud/spreed-ios#1430]
## Steps to reproduce
1. Login with domain, user and password
2.app crashes
3.after app start, app crashes immediately 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## Device information

**Device:** iPhone 13 mini

**iOS version:** 17.1.1

**Talk version:** 17.1.2

## Server information coming soon

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`)

**Talk version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`)

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by SystemKeeper** [comment]
See #1428
