### ISSUE TITLE
"Unable to load file" when pressing on any file

### ISSUE THREAD

**Issue by xeonixo** [nextcloud/spreed-ios#1455]
## Steps to reproduce
1. Send or Recieve any File - for example an Image
2. Tap on the File to open it

### Expected behaviour
Open the Image/File. This definitly works on Android Devices with the same server....

### Actual behaviour
Error Box "Unable to load File" with option "OK" instead of opening the image...

## Device information

**Device:** iPhone 15 Pro

**iOS version:** 17.2

**Talk version:** 18.0.0

## Server information

**Nextcloud version:** 27.1.4
**Talk version:** 17.1.3

**Custom Signaling server configured:** yes - df65394c1204ea4ba1c7da1909715f4d4f59b3ef

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

### Server log (data/nextcloud.log)
Could not be provided at the moment

Side note: server file encryption is enabled

**Comment by SystemKeeper** [comment]
Could you please check if this happens on a newly created user as well?

**Comment by xeonixo** [comment]
hi, sorry for late reply.

> Could you please check if this happens on a newly created user as well?

Works with a new user. I created a Group Chat and sent an image. i was able to open that image.

Do you have a solution for "old" users?

**Comment by SystemKeeper** [comment]
> Works with a new user.

Hm, I really expected this to fail as well 😅  So there must be something "special" about that particular user. Anything that recently changed for that user? Anything you know is "different" to other users?

Can you please post a screenshot of the error that is appearing?

**Comment by SystemKeeper** [comment]
I'll close this issue for now as there are information missing. If there are any further information, feel free to reopen it.
