### ISSUE TITLE
Unable to start/receive audio/video calls on Apple Silicon Mac

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#1487]
## Steps to reproduce
1. download app from Mac App Store
2. login
3. give microphone and video permissions to app
4. try to initiate a call, app on phone works but not on Mac

### Expected behaviour
There should be feature parity.

### Actual behaviour
I can neither see the phone/video buttons in the top contact bar while in a chat nor click it to see for example the previously shared images.

## Device information

**Device:** M1 Max MacBook Pro

**macOS version:** 14.2.1 (23C71)

**Talk version:** 18.0.0 (5)

## Server information

**Nextcloud version:** 28.0.0

**Talk version:** 18.0.0

**Custom Signaling server configured:** yes

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

**Comment by SystemKeeper** [comment]
> I can neither see the phone/video buttons in the top contact bar while in a chat nor click it to see for example the previously shared images.

This depends on the width of the window. If the window is too narrow, the titlebar and the buttons disappear. Looks like the width calculation is different when running on macos.

**Comment by e-caste** [comment]
Okay, very interesting. But as you can see from my screencap below, these buttons and the name disappear and the top bar becomes unclickable when the window is still quite wider than needed to show them.

https://github.com/nextcloud/talk-ios/assets/48513706/e9c57893-0698-4e67-927a-9085e135e49e

Also, about receiving calls: I received one and only my phone rang, should I expect my Mac to ring too or not? And if yes, I think this is also a bug
