### ISSUE TITLE
Unable to send message reactions on Apple Silicon Mac

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#1488]
## Steps to reproduce
1. download app from Mac App Store
2. login
3. open chat

### Expected behaviour
When I right click on a message, I get the same options as holding down on iPhone.

### Actual behaviour
I don't get the menu to send a reaction.

Options on my own messages:
<img width="173" alt="Screenshot 2024-01-14 at 17 00 20" src="https://github.com/nextcloud/talk-ios/assets/48513706/a2251c1a-6aca-4c04-a608-71fb9478688a">

Options on others' messages:
<img width="141" alt="Screenshot 2024-01-14 at 17 00 54" src="https://github.com/nextcloud/talk-ios/assets/48513706/22dbae46-1e7c-40a6-a93f-66add830ed2e">

## Device information

**Device:** M1 Max MacBook Pro

**macOS version:** 14.2.1 (23C71)

**Talk version:** 18.0.0 (5)

## Server information

**Nextcloud version:** 28.0.0

**Talk version:** 18.0.0

**Custom Signaling server configured:** yes

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

**Comment by SystemKeeper** [comment]
Yea, the accessoryView (where you can select emojis when long pressing on the message in an iOS device) does not render on macos, that's why the option for adding a reaction is missing.

**Comment by e-caste** [comment]
Is there any plan for supporting this? Not having feature parity between platforms is not ideal from a UX perspective

**Comment by SystemKeeper** [comment]
Well, support was already there, before we had the auxillary view to directly select emojis (which does not render on macos).
