### ISSUE TITLE
Align mime type icons

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed-ios#1578]
- https://github.com/nextcloud/android/issues/12687
- https://github.com/nextcloud/talk-android/pull/3719

something to check/align

**Comment by nickvergessen** [comment]
New icon only touching issue https://github.com/nextcloud/server/issues/44340

**Comment by SystemKeeper** [comment]
The mime type alignment is done by https://github.com/nextcloud/talk-ios/pull/1730
