### ISSUE TITLE
Voice messages take up way to much space in the UI

### ISSUE THREAD

**Issue by LostEtienne** [nextcloud/spreed-ios#1630]
## Steps to reproduce
1.just Send a VoiceMessage on Talk-IOS

### Expected behaviour
They should look like in other apps

### Actual behaviour
![image](https://github.com/nextcloud/talk-ios/assets/120445159/1e8e154e-585d-4260-9ad1-16efd3a98975)

## Device information

**Device:** iPhone X/iPad Y/…

**iOS version:** 17.5

**Talk version:** latest

## Server information

**Nextcloud version: 28.0.4

**Talk version:latest

**Comment by SystemKeeper** [comment]
This should be fixed in the current beta version, can you test with https://testflight.apple.com/join/cxzyr1eO?

**Comment by LostEtienne** [comment]
> This should be fixed in the current beta version, can you test with https://testflight.apple.com/join/cxzyr1eO?


Yes, thank you that actually fixed it. When will this update roll out in the release version? Is there a date planned?

![image](https://github.com/nextcloud/talk-ios/assets/120445159/5c36245b-20bc-4f18-b1d7-f22e2eea5f04)

**Comment by SystemKeeper** [comment]
Shouldn't take too long 🤫
