### ISSUE TITLE
cannot create personal private conversation in iOS client 19.0.0

### ISSUE THREAD

**Issue by WuQio** [nextcloud/spreed-ios#1655]
**Is your feature request related to a problem? Please describe.**
The newest version of iOS client is 19.0.0 in Chinese App store, there's no entry to create private conversation. And when my friends create a group conversation and send some messages, my iOS client does not notify me. Only when I open the APP, I see the message.

**Describe the solution you'd like**
Maybe there should be a entrance to create a private conversation just like version 18

**Describe alternatives you've considered**

**Additional context**

**Comment by SystemKeeper** [comment]
The conversation creation processes will be reviewed as part of https://github.com/nextcloud/spreed/issues/12294.
To create a private conversation on talk iOS you just search for the user in question (as you’d do in web)

**Comment by WuQio** [comment]
Thanks, I see
