### ISSUE TITLE
Open app by html link

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/spreed-ios#1667]
## Steps to reproduce
1. create a link like „nextcloud-talk://cloud.example.com“
2. click on the link
3. app not opens

### Expected behaviour
If I click on the link „nextcloud-talk://cloud.example.com“ the talk app should start. Only a simple start is needed.

### Actual behaviour
It is not possible to link the Talk App. If I create a link like „nextcloud://cloud.example.com/“ the Nextcloud files app opens. But this is not working for the talk app. 

## Device information

**Device:** iPhone 12 mini

**iOS version:** 17.5.1

**Talk version:** 19.0.2

**Comment by SystemKeeper** [comment]
Just use `nextcloudtalk://` to start the app.

**Comment by Dennis1993** [comment]
Thank you very much! That's awkward :D
It works perfectly! But only on iOS and not on Android. Is it right?

**Comment by SystemKeeper** [comment]
> But only on iOS and not on Android. Is it right?

Honestly, I have no idea 😅 You might want to create a feature request at the talk-android repo for that: https://github.com/nextcloud/talk-android

**Comment by Dennis1993** [comment]
ok, **THANKS**!!!
