### ISSUE TITLE
Unable to update from Mac App Store - need to uninstall and reinstall every time to keep app updated

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#1668]
## Steps to reproduce
1. install app from Mac App Store
2. wait for update
3. click update in Mac App Store

### Expected behaviour
The app updates

### Actual behaviour
<img width="477" alt="Screenshot 2024-05-23 at 09 51 44" src="https://github.com/nextcloud/talk-ios/assets/48513706/46fce2cd-9c74-49bc-99f1-972cb7560b94">

## Device information

**Device:** MacBook Pro M1 Max

**macOS version:** 14.5 (23F79)

**Talk version:** installed 19.0.0 (8) -- updating to 19.0.2

## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`)

**Talk version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`)

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by SystemKeeper** [comment]
Just tested, works fine here:
<img width="738" alt="image" src="https://github.com/nextcloud/talk-ios/assets/1580193/a6224857-185a-4ba2-b46e-4514616b23d1">


I don't think this is something we can influence.

**Comment by e-caste** [comment]
any files that might prevent an update? it only happens with this app. I had previously installed Nextcloud Talk Desktop so maybe conflicting files?

**Comment by SystemKeeper** [comment]
> I had previously installed Nextcloud Talk Desktop so maybe conflicting files?

Talk Desktop and Talk iOS don't reference the same files. Since the iOS app is installed through the app store, it should be properly sandboxed. I fear this is nothing we can influence since we soley rely on the mechanism that is provided by apples app store.
