### ISSUE TITLE
Call screen does not fade/end when leaving conversation

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed-ios#1710]
## Steps to reproduce
1. Receive a call
2. See call notification on iPad
3. Leave the conversation on Desktop/Web

### Expected behaviour
Screen ends "soon"

### Actual behaviour
Screen stays for "45 seconds"

**Comment by SystemKeeper** [comment]
> 3\. Leave the conversation on Desktop/Web

Did you mean Join here?
I just tested, this works as expected for me. 

Two questions:
* It was the same account on iPad and Desktop/Web?
* The iPad was able to connect to that instance you tested it on?

**Comment by nickvergessen** [comment]
I received a call that is not interesting to me, so as a response I left the conversation (delete for me, but I'm not a moderator, so I just leave it eternally)
