### ISSUE TITLE
Option to lock the app with Face ID/ Touch ID

### ISSUE THREAD

**Issue by srijansaxena11** [nextcloud/spreed-ios#1714]
**Is your feature request related to a problem? Please describe.**
Majority of texting apps (WhatsApp, Telegram, etc.) have the option to lock the app with Face ID/ Touch ID. It would be great to have it on Nextcloud Talk as well as it is becoming more and more widely used.

**Describe the solution you'd like**
Option to lock the app with Face ID/ Touch ID like in WhatsApp/Telegram

**Describe alternatives you've considered**
Other apps already have this option to lock them with Face ID/ Touch ID

**Additional context**
N/A

I am up for testing if required. I have the certificate to sign the IPA and sideload it on my iPhone for testing and/or can test it via TestFlight as well.

**Comment by srijansaxena11** [comment]
Forgot to mention, the official Nextcloud (File Management) app for iOS also has the option to lock the app with Face ID/ Touch ID.

**Comment by SystemKeeper** [comment]
Thanks for posting your idea! I'd like to add another alternative: The upcoming iOS 18 allows locking apps natively, so I don't think it makes sense to put a lot of effort in this feature from our side.

**Comment by srijansaxena11** [comment]
> Thanks for posting your idea! I'd like to add another alternative: The upcoming iOS 18 allows locking apps natively, so I don't think it makes sense to put a lot of effort in this feature from our side.

Oh yes! Completely forgot about that. Thanks for reminding. Will wait for iOS 18 for it.
