### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by maghog** [nextcloud/spreed-ios#1737]
Please update translations from Transifex. Swedish is 100% translated but app is still in english.

Thanks!

**Comment by SystemKeeper** [comment]
Transifex is automatically updated, lastely done this morning. Which app version are you using and which strings are not correctly translated?

**Comment by SystemKeeper** [comment]
Ah, seems you're right, the translation is not used inside the app. Seems that at some point the translation was not completed and therefore not included. We'll take a look. Thanks for the report!
