### ISSUE TITLE
Message grouping is missing some conditions

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed-ios#1828]
- iOS: https://github.com/nextcloud/talk-ios/blob/4c408f2f4d0ab8983d948219a39051de5154d526/NextcloudTalk/BaseChatViewController.swift#L2076-L2090
- Web: https://github.com/nextcloud/spreed/blob/f91e5dd440898ecce9f8c38893596c2913012224/src/components/MessagesList/MessagesList.vue#L501-L538

---

Main differences:
- Never group bot messages (apart from changelog bot)
- Also group system messages from different users

**Comment by SystemKeeper** [comment]
Did you notice an issue with that? 
  
> * Never group bot messages (apart from changelog bot)

The bots part is checked at a different place: https://github.com/nextcloud/talk-ios/blob/4c408f2f4d0ab8983d948219a39051de5154d526/NextcloudTalk/BaseChatViewController.swift#L2008-L2012 

> * Also group system messages from different users

This is handled at https://github.com/nextcloud/talk-ios/blob/4c408f2f4d0ab8983d948219a39051de5154d526/NextcloudTalk/BaseChatViewController.swift#L2100-L2103

**Comment by SystemKeeper** [comment]
> * (apart from changelog bot)

That part seems to be indeed unhandled here, but it would not be grouped anyway, since the messages are not within the time range anyway.

**Comment by nickvergessen** [comment]
> Did you notice an issue with that?

No, just read from the code while aligning with Android on expectations.
But seems indeed to behave correct for those things.
So sorry for the noise
