### ISSUE TITLE
iOS support for "Recognize email guests"

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed-ios#1847]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

- Follow up to https://github.com/nextcloud/spreed/issues/6098

---

## 🍏 iOS

- [x] Show email icon when no name is set
- [x] Show ? when "default Guest" name is used (?)
   Asked in https://github.com/nextcloud/spreed/issues/13606#issuecomment-2430258945
- [x] Show first letter on gray background like for normal guests when a name is set
- [x] Check mentions (note their guest ID is longer than the old guests actor id and therefore potentially the regex needs adjusting)
   Fixed in https://github.com/nextcloud/talk-ios/pull/1850
- [x] Check autocomplete
   Works fine, but shows always email avatar (see third task)
- [x] Check call view
   Works fine, but shows always email avatar (see third task)

**Comment by SystemKeeper** [comment]
* Show the invited email address on the "Guest name screen"

* Should we hide the "have an account, login here?" message from that screen?

I assume both are not relevant, as we can’t login as a guest via talk-iOS?

**Comment by nickvergessen** [comment]
yeah sorry, just copy-pasted from frontend
