### ISSUE TITLE
Location shared by maps leads to app crash

### ISSUE THREAD

**Issue by Ho551** [nextcloud/spreed-ios#1921]
## Steps to reproduce
1. Share a location via app maps in NC Web Interface
2. Open conversation with shared location
3. Talk app crash immediately

### Expected behaviour
Open conversation like when a location is shared by Talk app in iOS

### Actual behaviour
When a location is shared in the NC Web Interface via app maps (Location -> share to conversation) the Talk app crashes when opening the conversation.

## Device information

**Device:** iPhone 15

**iOS version:** 18.2

**Talk version:** 20.1.0

## Server information

**Nextcloud version:** 30.0.4

**Talk version:** 20.1.0

**Custom Signaling server configured:** yes

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

**Comment by SystemKeeper** [comment]
Thanks for the report - I can confirm the behaviour, we are taking a look!
