### ISSUE TITLE
not receiving notifications on Ios

### ISSUE THREAD

**Issue by ahmedbenahmed** [nextcloud/spreed-ios#1931]
Im facing a problem with push notification in ios( push notification i working on android client with the same server)
I have done all steps to change identifiers 
and here what i changed on branding file 

NSString * const talkAppName = @"Deom Chat";
NSString * const filesAppName = @"Deom Drive";
NSString * const copyright = @"© 2024 XXXX Co";
NSString * const bundleIdentifier = @"com.XXXX.messenger";
NSString * const groupIdentifier = @"group.com.XXXX.messenger";
NSString * const appsGroupIdentifier = @"group.com.XXX.apps";
NSString * const pushNotificationServer = @"https://push-notifications.nextcloud.com";

**Comment by SystemKeeper** [comment]
Push notifications will not work with self compiled versions of talk-ios:
https://github.com/nextcloud/talk-ios/blob/2bd72fc721d1fd40eeae57b1146f139272c97711/docs/notifications.md?plain=1#L95

It will only work with the official builds. The only alternative are branded clients as part of our branding offering.

**Comment by ahmedbenahmed** [comment]
How can we do to be a branded client

**Comment by SystemKeeper** [comment]
Best would be to reach out to the sales colleagues  at https://nextcloud.com/get-a-quote/  

Some Details about branding: 
https://nextcloud.com/features/#branding
