### ISSUE TITLE
Nextcloud Web Portal when logging into the talk app

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/spreed-ios#621]
## Steps to reproduce
1.Download Talk APP
2. Sign in
3.

### Actual behaviour
Some of my users are getting the Nextcloud we portal when logging into the talk app and not the talk app display. Please see below

## Device information

**Device:** iPhone X/iPad Y/…
iPhone 12 Pro
**iOS version:** 10/…
15
**Talk version:** 11.1.1
12.2.0
**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`)
22.1.1
**Talk version:** (see apps admin page: `/index.php/settings/apps`)
12.1.2

![image](https://user-images.githubusercontent.com/59488153/134399351-1182a515-f299-41a0-bfb7-023dd0f696c2.png)

**Comment by nickvergessen** [comment]
Either your server/proxy is misconfigured (breaking the nc:// redirect) or your server errored while doing the login.
