### ISSUE TITLE
Audio & Mic Stop Working after transferring session 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/spreed-ios#623]
## Steps to reproduce
1. Join Call via IOS APP 
2. Stay a while & leave call and rejoin via web
3.

### Actual behavior
Once on a call with a user we are both on the call via talk ios app and after a while one of us leaves the call and joins via web we're able to see each other but can hear each other and the user using the talk ios app has to leave and rejoin via ios app and it starts working. I'm not sure if this is a bug that belongs here or under talk ios. 

## Talk IOS app
12.2.0
**Talk app version:** (see apps admin
12.1.2
**Custom TURN server configured:**
Yes
**Custom STUN server configured:**
Yes

**Comment by SystemKeeper** [comment]
Are you using HPB or internal signaling?

**Comment by AndyXheli** [comment]
internal signaling  I don't recall having this issue on talk app v 11 just started on v 12

**Comment by AndyXheli** [comment]
Have not had any issues in Talk 13
