### ISSUE TITLE
No push messages from any NC instances

### ISSUE THREAD

**Issue by jacotec** [nextcloud/spreed-ios#627]
I'm not getting any push notifications to any Talk/IOS devices since yesterday ... missed a lot of messages. Issue confirmed by other users and on four different NC installations.

Any issues with your Push Gateway? Push Certificate expired? ;-)

**Comment by jacotec** [comment]
Update: Chatmessages are pushing again, but Talk calls are not ringing.

**Comment by Ivansss** [comment]
Thanks for opening the issue @jacotec 
We are updating our push proxy at the moment. You should receive call notifications shortly.
Sorry for the inconvenience

**Comment by Ivansss** [comment]
Push proxy has been updated and call notifications should be working again! @jacotec
