### ISSUE TITLE
Getting Folder\file web view when logging into talk app

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/spreed-ios#669]
## Steps to reproduce
1. Download Talk 
2.Enter server url
3.Enter username & password
4. Enter TOTP Key

### Expected behaviour
Should populate the talk app view

### Actual behaviour
Some users are getting folder\file web view when user removes and redownloads the app it takes them to the correct view user may have to do this multiple times

## Device information

**Device:** iPhone X/iPad Y/…
iPhone 12 Pro
**iOS version:** 10/…
15.1.1
**Talk version:** 11.1.1
12.4.0
## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`)
22.2.3
**Talk version:** (see apps admin page: `/index.php/settings/apps`)
12.1.2
![2021-11-18 09-28-46-0](https://user-images.githubusercontent.com/59488153/142447116-2face95c-c586-4357-bc9f-c4436d9b7653.png)

**Comment by Ivansss** [comment]
This is not a bug in the Talk iOS but it sounds like it could be related to:
https://github.com/nextcloud/server/pull/29752

**Comment by AndyXheli** [comment]
@Ivansss thank you very much! hopefully  nextcloud/server#29752 will fix the issue.
