### ISSUE TITLE
iOS 12.5.5 | Nextcloud Talk v13 application crashes

### ISSUE THREAD

**Issue by adieperi** [nextcloud/spreed-ios#679]
## Steps to reproduce
1. Install Nextcloud Talk v13 on an iPhone 5s.

### Expected behaviour
The application should start as usual.

### Actual behaviour
Once connected to a Nextcloud server, the application crashes, and even if I shut down the application process and restart it the application crashes again.</br>
I should mention that I have already tried to delete the application and reinstall it.

## Device information

**Device:** iPhone 5s

**iOS version:** 12.5.5

**iPhone Talk version:** 13

**Server Talk version:** 12.1.2

**Comment by SystemKeeper** [comment]
Thanks @adieperi for the report! This bug was recently discovered and affects iOS versions < 13. It‘ll be fixed in an upcoming version. Sorry for the trouble.

**Comment by Ivansss** [comment]
Fixed in #680 
Bugfix has been included in Talk iOS version 13.0.1. (which will be available tonight or tomorrow in the App Store)
Sorry for the trouble 😬
