### ISSUE TITLE
Can't use latest app with older server (Talk 12)

### ISSUE THREAD

**Issue by danir-de** [nextcloud/spreed-ios#689]
## Steps to reproduce
1. Have a Nextcloud 22 server with Talk 12
2. Use the latest Nextcloud Talk app (for v.13)
3. Try to make an audio or video call

### Expected behaviour
P2P connection (with turn server) should be established and you'd be able to make a call with other app and web users.

### Actual behaviour
You can only make calls with other app users - connection to talk users on the browser cannot be established - even when all people (2 browser users & 2 app users) are in the same call.

Since the apps auto-update, it's not possible to stop this from happening in the future for all users.

## Device information

**Device:** Galaxy S10 & iPhone 12

**Android version:** Android 11 / iOS 15

**Talk version:** 13 (App)

## Server information

**Nextcloud version:** 22.2.3

**Talk version:**  12.1.2

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

### Server log (data/nextcloud.log)
<details>

```
nothing was generated around the time of testing
```
</details>

**Comment by SystemKeeper** [comment]
Hey @danir-de thanks for the report! Just to clarify:
* You start a call from talk-web
* You try to join from talk-ios
* Does nothing happen or does web see ios and not the other way round?

With talk-ios 12.4.0 everything worked? Just by looking through the commit history beginning with 12.4.0 I didn't spot obvious changes regarding signaling or something.

**Comment by danir-de** [comment]
Hello @SystemKeeper, I've tested it last week before any updates were installed to the clients. 
I've got an iPad which (hopefully) doesn't auto-update, so I'm gonna test with that one as well and report back.

The android and iOS devices can join the call and connect to each other, but won't have a connection to the desktop users.
On the mobile, the video screen just remains black and on the web we're seeing the loading spinner on top of the phone-users profile picture. 

![image](https://user-images.githubusercontent.com/4672840/144621062-f72b6f53-cadf-4114-b535-5a2df2644142.png)

**Comment by danir-de** [comment]
I could verify that it's working with Talk 12.4.0 but I have a suspicion that something else is going on and will test with 13.0.1 again.

**Comment by SystemKeeper** [comment]
Ok, please let us know 👍

**Comment by danir-de** [comment]
I could bottle the problem down to being an IPv6 / IPv4 problem where clients are in different network environments (IPv4 only or DS-Light (IPv6 & _shared IPv4_). 

I'm closing down this issue - thank you.
