### ISSUE TITLE
No Call notifications when app is closed

### ISSUE THREAD

**Issue by DwinAnderson** [nextcloud/spreed-ios#693]
## Steps to reproduce
1. Two iPhones XR, Nextcloud Talk is opened on both devices.
2. I minimize the application and close it on both devices.
3. I choose one of two phones (randomly, as an example let it be "phone №2"), open the application through the application icon, then go to the chat with user and make a 1 to 1 call.
4. No call notification on "phone №1". 
Remarks:
1. When app is opened on both phones, there is no such problem! 
2. Message notifications arrive in both cases (when users are in app at this moment and even they are not, and even apps are not launched in the background at all).

### Expected behaviour
Call notification should be even app is not launched or even it is launched but in the background.

### Actual behaviour
No call notification when app launched in the background or when it is not launched.

## Device information

**Device:** iPhone XR number 1 and iPhone XR number 2

**iOS version:** both have iOS 15.1.

**Talk version:** both have 13.0.1.

## Server information

**Nextcloud version:** 22.2.3

**Talk version:** 12.2.2

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no

**Comment by DwinAnderson** [comment]
All the previous issues about problems with call notifications were closed or forwarded to chat notifications problems. This problem wasn’t solved for long times. Please, is it possible at all to get normal call notifications? Maybe settings for personal notification server?
Btw Android users have fix for this notifications problem from 2018th already, then they had problems again in 2020th but everything was solved again. 
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server
” You’re responsible for setting up a provider server (or servers) and for configuring your app to handle notifications on the user’s device. Apple manages everything in between, including the presentation of notifications to the user.”
May be notifications are not safe at all?
I’ve read about sideloading apps, is it possible for nextcloud talk, so I could configure it in my way to get all the notifications from my personal apn server?

**Comment by SystemKeeper** [comment]
Hey DwinAnderson,

as far as I can see, there're no known issues regarding push notifications. I just tested the scenario you described and it worked as usual.
You might want to check the following document about `occ notification:test-push` and see what happens: https://github.com/nextcloud/talk-android/blob/master/docs/notifications.md#-check-server-settings
Other than that try to remove your account from talk-ios and re-add it. Also check your server logs for any errors or exceptions. 
If you can access the console of your iPhone (via MacOS), you might want to check for any messages from `NextcloudTalk` or anything regarding push.

**Comment by DwinAnderson** [comment]
Hey, thank you! Tried occ notification and it gives this:

"Trying to push to 5 devices

Language is set to en
Private user key size: №№№№
Public user key size: №№№
Identified 1 Talk devices and 4 others.

Device token:№№№
Device public key size: №№№
Data to encrypt is: {"nid":№№№№,"app":"admin_notification_talk","subject":"Testing push notifications","type":"admin_notifications","id":"№№№№№№№№"}
Signed encrypted push subject
Push notification sent successfully"

I can't understand why there are "5" devices if user is authorized only in Nextcloud Talk and one session is in web-browser? Any other sessions were closed through user's security panel. Also I can't understand why text push goes so long, it takes for about 30 seconds, btw in push on iPhone it says that "You recieved a new notification that couldn't be decrypted". **I haven't told that I have problems with text pushes, only with call pushes!**
I've closed all the sessions in user1 profile and user2 profile, so I was need to login into Nextcloud Talk again on both devices. That didn't bring results.
Also I've looked through nextcloud.log and it looks like porridge, everything is simply thrown over there without a clear division, so it is not clear what can be found there at all. 
On /settings/admin/overview page it is written that "All checks passed". Maybe any other ideas?

**Comment by SystemKeeper** [comment]
> Identified 1 Talk devices and 4 others.

I guess you have 4 devices not related to talk? Like the Nextcloud files app ?

Might be possible, that the test notification can’t be decrypted, not sure, need to have a look.

What would be interesting: Does this notification appear, even when talk is closed ? (As this was your main problem)

**Comment by DwinAnderson** [comment]
I've looked through /settings/admin/logging (it is more informative), yes there are some errors, but they are a little bit old, so no errors at the moment when push arrives or a moment earlier before that. Seems like logs are ok. 
Yes, you are right, I have Talk, Passwords and Nextcloud app also, so there are 3 apps on each of the iOS devices, but I've logged out everywhere, even then in web-browser. 
> Might be possible, that the test notification can’t be decrypted, not sure, need to have a look.

Every time I executed "sudo -u nginx /usr/share/nginx/nextcloud/occ notification:test-push --talk MyUser" I've received such notification after about 30 seconds where it says that "You recieved a new notification that couldn't be decrypted". If I tap on it, Talk app opens on the last place where I was before closing it and nothing happens. What is interesting (maybe) that according to that instruction you sent me, I shouldn't have received any notification.
> What would be interesting: Does this notification appear, even when talk is closed ? (As this was your main problem)

Yes, it does :/ App was closed, 1 minute pass (to be sure), command was executed and after about 30 seconds this notification was received. And no logs at this moment on the page /settings/admin/logging (all log levels are turned on).

**Comment by SystemKeeper** [comment]
I wouldn’t worry too much about the 30s. I assume it’s the fallback („last chance“) to display a notification (there’s a timeout how long a background process is allowed to process notifications, if it exceeds, iOS tries one last time to convince the app to show a notification, which results in the decrypt message).
So in General push is working and it’s working when the app is closed.

**Comment by SystemKeeper** [comment]
> What is interesting (maybe) that according to that instruction you sent me, I shouldn't have received any notification.

That’s the case for android, so might be different for iOS (see above)

**Comment by DwinAnderson** [comment]
Hmm... After you've told about occ notification, I've tried more search about this decrypted message and found in google webarchive that in 2020th some user received such notification too, and yes, it is iOS theme, on Android devices there will be no botification at all and on iOS it looks like this. I'll quote him, so to : 
"return Push notification sent successfully but on iOS the client receives a new notification with text “New notification : You received a new notification that could not be decrypted” on Android client nothing happens. Reauthenticating apps does not change anything.". And there some guy adviced this "https://gitlab.com/Nextcloud-Push/direct-push-proxy-v2". But seems like it is totally different problem of what I faced with, because topic of that problem sounds like "Group notifications aren’t working on mobile devices iOS/Android". So yes, it is normal that iOS gives such push. 

> So in General push is working and it’s working when the app is closed.

Yes.

**Comment by DwinAnderson** [comment]
It is a late problem that was in #582 and then it was closed and all the discussion moved to #595. But in #595 it was solved only about messages, not calls :(

**Comment by SystemKeeper** [comment]
> I've tried more search about this decrypted message

As I said, don't worry about this too much, as this is expected in the current version of talk-ios. I'll add some changes to correctly display the test-message. 

What country are you using your iPhones in?

**Comment by DwinAnderson** [comment]
Hey, SystemKeeper! 
Seems like at this moment (after 20 hours of testing) problem is solved. I receive call notifications regardless they are only voice calls or with video. I've created calls with different time intervals from device1, then from device2, while in all cases the application was opened only on one of the devices and lately even without running Talk application (from iOS phone book app).

I've made such procedures for this solvation:
- Deleted Talk app from Nextcloud and installed it again (but for sure if was updated to the last version before that);
- Closed all sessions for these 2 users from their nextcloud profiles (seems like this was the main problem, but I'm not sure, but what I am 100% sure in is that lots of sessions were dead even Nextcloud wrote that they were active - what is strange for me, but ok);
- Removed Talk app from both devices and installed it again through App Store (I've done that earlier, but just in case);
- After I logged in on two devices in their two different profiles (of course), app asked me for permissions to contacts, gave it on both devices. Then on the device1 went to the conference with user2 and on the device2 went to the conferece with user1. Strange thing was there, because on device1 I've received phone ico about immediatelly and on the device2 it was infinitely spinning circle ico. 5 minutes passed and nothing changed, so I've made call from device1 to device2, gave permissions on device1 to mic and to my surprise, call passed and appeard on device2, accepted it and then ended. Phone ico on devce2 appeared too instead of that spinning circle. Called vice versa. Successful too. Later gave permissions on both devices during video call.

I suppose that maybe first call is most important... Because earlier I didn't wait for that spinning circle, ended call, reloaded app, I remember that there was no spinning circle after that, but all that I wrote upper maybe sounds like crazy raving. Shaman games. But as a result, it seemes "raining".

> What country are you using your iPhones in?

It is a very difficult question, I'm in one country and my Phone account and my server lives in another.

**Comment by SystemKeeper** [comment]
> It is a very difficult question, I'm in one country and my Phone account and my server lives in another.

Well, in worst case that would be 3 countries...

I added some changes in #694 to get rid of the "...that could not be decrypted" notification. 

Cool that it's working now for. I'll close this then.

**Comment by DwinAnderson** [comment]
Yep, thank you very much for your help! You're cool! =)
