### ISSUE TITLE
Encrypted push notification

### ISSUE THREAD

**Issue by ezforw** [nextcloud/spreed-ios#696]
Hi, this is maybe more of a question then an issue. Sorry if this is the wrong place to ask.

I’m just wondering if the push notification payload of the nextcloud iOS talk app is encrypted or it is sent using clear text?

I am aware the Android version is using some sort of encryption as discussed here, https://github.com/nextcloud/talk-android/issues/393, so wondering if the iOS app have something similar?

**Comment by SystemKeeper** [comment]
Hey @ezforw 
Yes, the iOS app does use the same thing. The payload is encrypted by the NC instance before sending it to the push proxy and decrypted on the device itself. 
You can see this at https://github.com/nextcloud/talk-ios/blob/6f13f1270f40b5cfbf44d10877434ddcaa1dfa06/NotificationServiceExtension/NotificationService.m#L91-L98 for example
