### ISSUE TITLE
Allow to select audio output channel

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed-ios#712]
It should be possible to select the audio output (speaker, earphones, bluetooth, ....)

Ref [It should be possible to select the audio output (speaker, earphones, bluetooth, ....)](https://github.com/nextcloud/talk-android/issues/1761)

**Comment by SystemKeeper** [comment]
Might also solve #562

**Comment by nickvergessen** [comment]
Yes I guess so
