### ISSUE TITLE
Login via iOS app from M1 Macs not working

### ISSUE THREAD

**Issue by MariusQuabeck** [nextcloud/spreed-ios#728]
I've tried to login to Nextcloud Talk from the app on my M1 Mac to have a standalone talk app instead of a browser tab.
Unfortunately, login doesn't work, claiming wrong username or password. I've just verified this with @Ivansss, login credentials are definitely correct.
We've also tried different nc servers and users, with and w/o 2FA enabled, same issue.
I also gave NC Talk full disc access permissions, same issue.

I'm trying this from my MacBook Pro (13", M1, 2020) using Nextcloud Talk 13.1.1 (1).

Happy to help to debug this but I'd need pointers for how to do so :)

**Comment by nickvergessen** [comment]
Either this is a Nextcloud server issue or an iOS app issue.
I heavily doubt a Talk server app issue.

**Comment by MariusQuabeck** [comment]
we've tried our personal nc servers and the company one. same issue everywhere 🤷

**Comment by Ivansss** [comment]
I will move this to the talk-ios repo this issue.
Sorry @MariusQuabeck I should have told you to open the issue there 😅

**Comment by SystemKeeper** [comment]
This did work properly for me 🤔 I’ll try again. One quick idea: can you try changing the password to something „simple“ and try again? Or can you try to copy and paste your password, to rule out that we‘ve got a problem with keyboard layout or something?

**Comment by SystemKeeper** [comment]
> One quick idea: can you try changing the password to something „simple“ and try again? Or can you try to copy and paste your password, to rule out that we‘ve got a problem with keyboard layout or something?

~Okay, scratch that. Just tested again and indeed, login does not work anymore with 13.1.1 on NC 23.0.0.~

**Comment by SystemKeeper** [comment]
@MariusQuabeck Are you pasting your password in? I've noticed that my password appears twice after pasting. When I enter it manually I can login successfully. Not sure if this is specific at my setup here (I'm remoting in to my Mac), just wanting to check.

**Comment by MariusQuabeck** [comment]
I've changed it to something simple and typed it in manually. didn't work.

**Comment by MariusQuabeck** [comment]
alright update: it works if you use email instead of username for login and I can also confirm the double paste issue. it took me 10 minutes to type in our secure password for c.nc.c 😂
thanks @Ivansss & @SystemKeeper

**Comment by SystemKeeper** [comment]
> it took me 10 minutes to type in our secure password for c.nc.c 😂

Feel you ;-)

If you like @Ivansss you can assign me here.

**Comment by SystemKeeper** [comment]
It looks like it only happens if you use CMD + V, if you use the menubar to paste the password, it looks like its correctly pasted (only once). Maybe you could try this @MariusQuabeck and confirm?

**Comment by MariusQuabeck** [comment]
can confirm, double paste only happens via cmd+v, pasting via menu bar works as expected, left-click in username or password field crashes the app

**Comment by SystemKeeper** [comment]
> left-click in username or password field crashes the app

I noticed this as well. Will post it later as an issue, so we have it tracked

**Comment by SystemKeeper** [comment]
Looks like there's a workaround by subclassing WKWebView https://developer.apple.com/forums/thread/696525?answerId=708067022#708067022 
I tested this and it works. If we want to go that route, I can submit a PR.
