### ISSUE TITLE
nextcloud talk on ipad air 12.5.5 just ring once, no accept and decline menu shows up

### ISSUE THREAD

**Issue by czjjwx** [nextcloud/spreed-ios#733]
Steps to reproduce
1.install nextcloud talk on ipad air Version 13.1.1
 

Expected behaviour
when a user call me ,the "accept and decline menu" should show up. So, I can answer a call by taping the accept button.

 Actual behaviour

1.when someone  call the user login in iapd, the ipad screen just flash once with a sound. 
2. no "accept and decline menu" shows up
3. If  I turn on notification before someone call me , when a call is coming in ,tap a notification menu, you can make a choice for voice or video or cancel the call.
4. if you missed the notification, you can find nothing to access the call.

Device information

iPad AIR MODEL NUMBER MD786LL/A

iOS version:12.5.5

Talk version: 13.1.1

 Server information

Nextcloud version: 22.2.3

Talk version: 12.2.3

I have another ipad air works well. 
device information :
model : MF016LL/A
Version: 12.5.5 
Talk version: 13.1.1
use the smae server

**Comment by Ivansss** [comment]
Hello @czjjwx 

> If I turn on notification before someone call me...

What do you mean by that? What are your notifications settings for Talk?

**Comment by czjjwx** [comment]
If you turn off  the notifiction of talk, I cannot answer a call. After you turn on the notification of talk, when someone call you, a notification pops up. You have three choices, voice, video, cancel. The notification persists 4-5 seconds. If you missed it, you can not answer the call.

**Comment by SystemKeeper** [comment]
What happens if you enter the conversation and touch the camera icon on the tap to join the call?

**Comment by czjjwx** [comment]
when you enter the conversation and touch the camera icon ,  I can connect to others if I saw someone start a call.

**Comment by SystemKeeper** [comment]
Hm, I‘m not sure I understand your problem then. When you disable notification, the only way to „answer“ a call is to manually join it.

A call notification will last for 45s. It will be closed earlier if you accept the call on another device (say iPhone and iPad are ringing and you answer on the iPhone, your iPad will close the notification), or if the person who started the call left it => nobody is in the call.

**Comment by czjjwx** [comment]
sorry, no.
I talk about a ipad air nothing else. notification last for 5 seconds. thank you.

**Comment by Ivansss** [comment]
Hi @czjjwx again :)

So you are getting just a normal push notification in that specific iPad when someone calls you, right?
It seems that, for some reason, you are not receiving a VoIP push notification that makes an incoming call screen to appear.

> I have another ipad air works well.

Is this iPad running the same iOS version (12.5.5) as the one where it is not working?

Have you tried to remove the account from the iPad where you have problems and add the account again?

**Comment by czjjwx** [comment]
yes, same 12.5.5 mentioned  above.  same server. I tried to reinstall  the app and creat a new account to login. doesn't work.

**Comment by SystemKeeper** [comment]
Hey @czjjwx 
There have been a few improvements to push notifications in the last 2 versions, can you please verify you’re using 14.0.3 and check again? If the problem persists, can you try to make a short video of the behaviour you’re encountering?
