### ISSUE TITLE
Errormessage missing when voicemessage upload fails 

### ISSUE THREAD

**Issue by crustulumtheoneandonly** [nextcloud/spreed-ios#741]
iPhone SE (MLM72DN/A)
iOS 15.3.1
Talk 13.1.1
NC 23.0.2
Microfon and Camera is allowed
Wi-Fi + Internet connected
All other iPhones work as expected

### Expected behavior:

When pushing the microphone button in the chat the recording of the voice message should start and when releasing the message should send.

### Actual behavior:
When pushing the microphone button to recording is automatically cancelled after 10 seconds and no messages is sent.

**Comment by SystemKeeper** [comment]
Hi @crustulumtheoneandonly 
Does sharing in general work on this particular phone (picture for example)?

Maybe you can try one of the other accounts where voice messages are working? So anything permission related can be ruled out.

**Comment by crustulumtheoneandonly** [comment]
Found the cause for the Problem. Actually the user had no account disk space left. (Storage quota)
Thankfully a error was shown when uploading a picture. Sorry for the false alarm. 

Voice messages are working as expected on iPhone SE✅

**Comment by SystemKeeper** [comment]
Thanks for the feedback! Ich think we still should look into this and improve the error handling / user feedback.
