### ISSUE TITLE
No audio in calls joined as video in CarPlay with limited permissions 

### ISSUE THREAD

**Issue by MariusQuabeck** [nextcloud/spreed-ios#743]
I’ve just been in our internal company call and I don’t have any permissions to speak or stream video/screen there. 
If you join via the video icon button instead of the phone icon then I’m unable to hear anyone via CallKit/CarPlay.
Call duration timer works as expected and there is no visual feedback that something is wrong. 
I had to join via the phone icon button and then I was able to hear people in the call. 

Sorry, this one is literally written from the car :)
![A4E28C3D-2E3A-41FD-B781-D0936298A3D3](https://user-images.githubusercontent.com/17063564/159504766-0fcc38c4-ce54-419b-b7c5-1394366c581a.png)

**Comment by MariusQuabeck** [comment]
Just verified, it’s the other way around, no audio via phone icon, audio working via video icon. Can’t edit description and title from mobile, will do later

**Comment by MariusQuabeck** [comment]
Interestingly enough, I’ve got out of the car, disconnected the call, switched to AirPods, got back into the call in “video mode”, got back into the car and CarPlay took over again and that time it works from “video mode” 
![172DECC8-74CC-4D68-8CB6-E96451F92148](https://user-images.githubusercontent.com/17063564/159508372-5cffe812-1294-49e6-a2d9-cbe4bfbf6cc4.png)

**Comment by SystemKeeper** [comment]
That’s an interesting one 😄 
I don’t have a CarPlay enabled car (sadly), but I’m wondering if this is solved by #735 ?! Might be worth checking, after the next update is released.

**Comment by MariusQuabeck** [comment]
Will do :)

**Comment by SystemKeeper** [comment]
Hey @MariusQuabeck 
As #735 is merged and released, did you get a chance to test if this is working properly now?

**Comment by MariusQuabeck** [comment]
looks like I'm gonna do the next company call from the car then :) I'll let you know!

**Comment by SystemKeeper** [comment]
Hey @MariusQuabeck 
Got a chance to have a call in the car yet? 😉

**Comment by MariusQuabeck** [comment]
Hey @SystemKeeper not yet unfortunately! I'll try to join our company call today from the car.

**Comment by MariusQuabeck** [comment]
It was working properly yesterday, I'll do some further testing but this seems resolved.

**Comment by SystemKeeper** [comment]
Thanks for testing 👍 I’ll close this for now, feel free to open it again if there’s still a issue!
