### ISSUE TITLE
Add chat messages search for text and files

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#774]
**Is your feature request related to a problem? Please describe.**
It would be very nice to be able to search within the messages of a chat (and also all chats at the same time). This issue is a duplicate of #511, but I'm opening it because I wanted to add that this is a feature that is already implemented, works well, and is quite responsive in the Nextcloud desktop app (I think it was introduced with Nextcloud 23).  
The server-side APIs should already exist, so I believe it's just a matter of implementing the right calls and interface in the app.

**Describe the solution you'd like**
Either 1, 2, or both:
1. The search bar in the main chat list view should also search within all chat messages
2. From a chat view, the user should be able to tap on the name of the chat and then in the chat info view there should be a search button / bar to search within that chat only OR there should be a search button which expands into a search bar in the chat view, near the chat name

Nice to have: also search within shared file names, events, anything that is indexed on the server.

Here's the search bar in the Nextcloud desktop app:
<img width="443" alt="Screenshot 2022-05-03 at 18 37 16" src="https://user-images.githubusercontent.com/48513706/166499213-58ccf38e-30e6-425c-b98e-56d97e1f9781.png">

Here are the corresponding results after searching the "test" string (notice that the desktop app in addition to messages also finds files, calendar events, conversations, etc. I think in the chat app only messages, conversations, and in-chat shared files should be considered -- I want to add that for efficiency purposes ideally the app would call a specific message-only API, but at least in my testing I've found that using the generic APIs that target everything indexed even searches with a long list of results are pretty quick to load on my server, in the 1 to 2 seconds range):
<img width="452" alt="Screenshot 2022-05-03 at 18 38 34" src="https://user-images.githubusercontent.com/48513706/166499586-eb46ad03-d927-43e5-b378-2dafe432b482.png">

**Describe alternatives you've considered**
Not relevant to this issue.

**Additional context**
My setup:
- Nextcloud Talk iOS 14.0.0 (btw the copyright year should probably be updated to 2022, near the version in the app)
- Nextcloud Talk server 13.0.5
- Nextcloud server 23.0.3.2 on Docker
- Nextcloud desktop for Mac 3.5.0

**Comment by thisIsTheFoxe** [comment]
Hi,
Thanks for your interest. 
Please note that searching for chat messages is done via the fulltextsearch app (i.e. unified search) which was introduced in Nextcloud 20. Afaik there it no option to search for messages from a single conversation (as you mentioned in point 2).
Implementing this would probably require this library update:
-  https://github.com/nextcloud/ios-communication-library/pull/102
