### ISSUE TITLE
Better in-chat media preview

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#776]
**Is your feature request related to a problem? Please describe.**
This is simply a UX issue that's been bugging me for quite a while. I don't know how hard it would take to implement but it sure would be nice.

Here's an in-chat image preview on Nextcloud Talk iOS and the corresponding view on Telegram (as an example; Whatsapp, iMessage and the other main chat apps do the same or very similar):

| Nextcloud Talk  | Telegram |
|--------------|-----------|
| ![IMG_BA085BFE980D-1](https://user-images.githubusercontent.com/48513706/166503030-28c7023c-b426-4a5a-8db5-f411579488a8.jpeg) |![IMG_77AC29D37603-1](https://user-images.githubusercontent.com/48513706/166503232-759961f1-37eb-42ce-af07-e93fb289b864.jpeg) |

**Describe the solution you'd like**
Images and videos should be previewed with a larger footprint, and possibly without their filename (at least in the chat view, it could be displayed when the media file is opened).

**Describe alternatives you've considered**
Not relevant to this issue.

**Additional context**
Using Nextcloud Talk iOS 14.0.0.

**Comment by e-caste** [comment]
@SystemKeeper I have cloned the repo and played with it a bit, although I'm not able to run it. If I understand correctly, the needed changes are:
1. detect if a file is a media file
2. if it is a media file, double `kFileMessageCellFilePreviewHeight` at line https://github.com/nextcloud/talk-ios/blob/d491188516ac8d9b514f4209658126ba87fcc07a/NextcloudTalk/FileMessageTableViewCell.m#L71 and double `_previewImageView.layer.cornerRadius` at line https://github.com/nextcloud/talk-ios/blob/d491188516ac8d9b514f4209658126ba87fcc07a/NextcloudTalk/FileMessageTableViewCell.m#L74
3. if it is a media file, don't display the title -> do not run this line https://github.com/nextcloud/talk-ios/blob/d491188516ac8d9b514f4209658126ba87fcc07a/NextcloudTalk/FileMessageTableViewCell.m#L88

**Comment by nickvergessen** [comment]
@e-caste sorry we missed your chat message. Feel free to check the chat again as now one colleague is able to reply.
