### ISSUE TITLE
Add last messaged chats to iOS share sheet

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#778]
**Is your feature request related to a problem? Please describe.**
Right now if we want to share a file to Nextcloud Talk we have to open the share sheet, then choose Nextcloud Talk, then choose the chat and finally share the file. It would be simpler and quicker to select directly the chat we want to share the file with from the share sheet, as other chat apps offer.

Example of share sheet grabbed from the web:
![](https://tapsmart-wpengine.netdna-ssl.com/wp-content/uploads/2018/07/sharesheet13-1.png)

**Describe the solution you'd like**
I think the solution has already been implemented by @SystemKeeper in #526. I'd love for it to be merged.

**Describe alternatives you've considered**
Not relevant.

**Additional context**
Currently referring to Nextcloud Talk iOS 14.0.0.

**Comment by SystemKeeper** [comment]
Implemented in #526
