### ISSUE TITLE
Add ability to add a caption when sharing media or file through iOS share sheet

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#779]
**Is your feature request related to a problem? Please describe.**
At the moment if we want to, for example, send an image to a Nextcloud Talk chat with a caption we have to:
1. choose the image
2. open the share sheet
3. choose Nextcloud Talk
4. choose the chat
5. send the image
6. open Nextcloud Talk
7. choose the same chat
8. send the caption separately

**Describe the solution you'd like**
It would be nice if we could add a caption directly to the image (or file) right before sharing it:

| What iOS Messages does  | What Nextcloud Talk could do ("Add a comment..." text field shamelessly stolen by Telegram share sheet) |
|--------------|-----------|
| ![IMG_0D9DB9533084-1](https://user-images.githubusercontent.com/48513706/166509333-962a340c-4384-41d5-bfe5-f5fa5196ca69.jpeg) | ![IMG_A7E2D717B9ED-1](https://user-images.githubusercontent.com/48513706/166510160-87e38b6a-b177-4136-84c4-e1e8a65ee43f.jpeg) |

This would result in the following steps:
1. choose the image
2. open the share sheet
3. choose Nextcloud Talk
4. choose the chat
5. add a comment
6. send the image

which would eliminate the hassle of having to manually open the app again just to add a comment to the shared media.  

The comment can be sent in a separate message following the media file, since I don't think Nextcloud currently supports captions.

**Describe alternatives you've considered**
Not relevant.

**Additional context**
Using Nextcloud Talk iOS 14.0.0.

**Comment by SystemKeeper** [comment]
Hi @e-caste 
Thank you for your ideas! I remember discussing this in the past and the problem was/is that media and text can’t be combined in a single message, so it would be 2 messages. But it would be possible, basically.
Any opinions @Ivansss ? Should we add a text field and send 2 messages?

**Comment by e-caste** [comment]
@SystemKeeper Yes, that was my idea as well:
> The comment can be sent in a separate message following the media file, since I don't think Nextcloud currently supports captions.

**Comment by Ivansss** [comment]
Interesting idea indeed :) As @SystemKeeper this is currently not possible due to the current API but sending a second message could be a workaround for implementing this feature.

**Comment by nickvergessen** [comment]
Server ref:
https://github.com/nextcloud/spreed/issues/5354

But we also have "metaData" already for shares, e.g. to mark voice messages different. Could also add a comment field on that.
However if we simply duck-tape that together into
> {file}
> "Inserted comment"

It would break the rendering currently done by the clients, so that would need a bit coordination

**Comment by SystemKeeper** [comment]
Should we implement this as two messages as a first step? We could chain the sending, first upload and post the file, then post a message directly after.
Changes to the gui would be the same as having server support for this, so needs to be done either way.

**Comment by nickvergessen** [comment]
I think we should wait and then bring and support this properly on all platforms in one cycle.

**Comment by SystemKeeper** [comment]
Fixed by #1407
