### ISSUE TITLE
Reaction bottom bar is breaking auto scroll

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed-ios#783]
1. Be in an active chat
2. All kind of messages receive reactions
3. If too many reactions happen without a new message being added in the meantime the view might shift to add the bottom bars so much that the offset is too big and we don't scroll automatically anymore.

**Comment by nickvergessen** [comment]
Cc @mahibi should check if that happens in android as well

**Comment by mahibi** [comment]
not happening on android. there the content above the reaction is moved upwards..
