### ISSUE TITLE
App menu on japan language!

### ISSUE THREAD

**Issue by bigAboo80** [nextcloud/spreed-ios#805]
1I installed app fron app store, and reinstall, but no effect - menu still on japan language
![image](https://user-images.githubusercontent.com/48507036/169796217-fa16c843-aaf4-4f5f-9333-43f7ecd8d304.png)

**Comment by Ivansss** [comment]
Can you check in iPhone Settings > Nextcloud Talk, what language do you have selected?
You should be able to change your preferred language there.

**Comment by bigAboo80** [comment]
Thanks, It works!
