### ISSUE TITLE
can not accept call on iphone if nextcloud (talk) is open in browser

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/spreed-ios#807]
## Steps to reproduce
1. open nextcloud (talk) on Desktop (macbook)
2. open nextcloud talk on iphone
3. ask someone to call you
4. only desktop rings

### Expected behaviour
Step 4 - desktop AND mobile phone should ring
5. select desktop OR mobile phone to answer

### Actual behaviour
Only desktop accepts answer, but conversation runs on iphone 

## Device information

**Device:** iPhone X/iPad Y/…
iphone 12 pro
**iOS version:** 10/…
15.4.1
**Talk version:** 11.1.1
14.0.1
## Server information
Hetzner NC-Cloud service

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`)
23.0.3
**Talk version:** (see apps admin page: `/index.php/settings/apps`)
13.0.5
**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/settings/admin/talk#signaling_server`)
No (probably)
**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`)
No (probably)
**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`)
yes
### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by Ivansss** [comment]
Hi @ferdiga :)

Do you receive chat messages notifications in your phone? Or you don't receive any notification at all?

> Only desktop accepts answer, but conversation runs on iphone

What do you mean by "conversation runs on iphone"?

**Comment by ferdiga** [comment]
- I receive message information (number of new messages is shown, but not the call) in the iphone , but no call notifications.
- "conversation runs on iphone" I accept on the desktop and talk on the iphone

**Comment by Ivansss** [comment]
Version 14.0.2 fixed some problems regarding push notification subscription process. #806 
Check if you receive push notifications with this version, also you can take a look to this [document](https://github.com/nextcloud/talk-ios/blob/master/docs/notifications.md) for further debugging.

**Comment by SystemKeeper** [comment]
Version 14.0.3 was just released with some additional fixes regarding the push subscription. Can you check if it works for you now @ferdiga ?
