### ISSUE TITLE
Improve error message when upload fails

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed-ios#827]
## Steps to reproduce
1. Start to upload image
2. Uploading fails because of a network error

### Expected behaviour
Show a user-readable message

### Actual behaviour
![image](https://user-images.githubusercontent.com/1580193/174097108-42c60044-902a-4055-914b-8e1d095907ea.png)

**Comment by DanielStandfest** [comment]
Seems to me like the error message already has been fixed.
@SystemKeeper 
![Image](https://github.com/user-attachments/assets/da437d24-b597-4987-b926-48844b712a77)

**Comment by SystemKeeper** [comment]
Indeed, that seems to be fixed in the meantime. Since we use the error from NextcloudKit it might be even fixed there without noticing. 

Thanks for checking 👍
