### ISSUE TITLE
Slowdown with long conversations

### ISSUE THREAD

**Issue by FediVideos** [nextcloud/spreed-ios#835]
## Steps to reproduce
1. Start a text conversation get it to a certain length (for me it was messaging with a couple of people every day for about a week)
2. Observe how long it takes to load a conversation

### Expected behaviour
App performance should remain the same

### Actual behaviour
App starts slowing down and becoming unstable when conversations go over a certain limit. Leaving the conversation and starting a new one (so that the previous messages are gone) brings it back to normal.

## Device information

**Device:** iPhone 11

**iOS version:** 15.5

**Talk version:** 14.0.2

## Server information

**Nextcloud version:**  24.0.1 (but this problem has been consistent over many versions)

**Talk version:** 14.0.2

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** yes

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by SystemKeeper** [comment]
Ref: https://github.com/nextcloud/spreed/issues/4305#issuecomment-1166674513

Hey @FediVideos 

thanks for the information! As I said in the other issue, I can't reproduce this here - I have conversations which exist for years now without a problem... 
What I'm wondering:

> 2\. Observe how long it takes to load a conversation

To be clear here, you can open the app as usual (and fast), but when you enter a room it's slow and you have to wait for the conversation to load or only new messages need long to load?

* Is this conversation created by you?
* How many participants are there?
* Does this only happen in group conversations or also in 1:1 ?

**Comment by FediVideos** [comment]
Yes, created by me

1:1 conversations

It will become very jerky, to the point where I can't get the keyboard to even appear when I press on the message writing section (the paperclip icon is greyed out when this happens, by the way). It will sometimes not let me scroll the conversation either when it is "stuck" like this. Waiting a bit lets you use it, but this waiting period takes longer and longer until the app is unusable.

As soon as the conversation is purged, everything goes totally back to normal.

I use a basic shared hosting service for my Nextcloud, so I don't know if this is related to the power of the server?

Interestingly, the other people use Android apps and don't see any problems. It's only me with the iOS app who sees this slowdown/jerkiness happening.

**Comment by SystemKeeper** [comment]
Hey @FediVideos,

just wanted to check in with you. Did something change for you in the latest updates or are you still seeing this kind of issue?
