### ISSUE TITLE
Can't view notification message body

### ISSUE THREAD

**Issue by fuzunspm** [nextcloud/spreed-ios#844]
### Expected behaviour
Notification preview is visible with message body

### Actual behaviour
Notifications are received but I can't view the message body of it. It wasn't like this before, like 2 weeks ago and I don't know what did break it

Screenshot below:

![Image 0](https://user-images.githubusercontent.com/12132746/179696824-8c74cacc-c2c9-4e33-be70-61094e2da6dd.png)

## Talk app

**Talk app version:** 14.0.3

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes
**Custom STUN server configured:** yes

## Server configuration

**Operating system**: Ubuntu

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 7.4

**Nextcloud Version:** 24.0.2

## Device information

**Device:** iPhone 13

**iOS version:** 15.5

**Talk version:** 14.0.2

**Comment by SystemKeeper** [comment]
Hey @fuzunspm 
Can you try 2 things please?
1. Just restart your phone to make sure the NotificationExtension is restarted
2. Logout and Login again, to make sure everything is properly registered

**Comment by fuzunspm** [comment]
> Hey @fuzunspm Can you try 2 things please?
> 
>     1. Just restart your phone to make sure the NotificationExtension is restarted
> 
>     2. Logout and Login again, to make sure everything is properly registered

logout/login fixed it, thank you
