### ISSUE TITLE
Multi-select photos & files for uploading - instead of the current one at a time

### ISSUE THREAD

**Issue by marcusquinn** [nextcloud/spreed-ios#846]
**Is your feature request related to a problem? Please describe.**
Currently, adding many photos or files to upload has to be done one at a time with the + and selecting source repeatedly.

**Describe the solution you'd like**
Ability to multi-select photos to upload, the same as with the main Nextcloud Files app.

**Describe alternatives you've considered**
The Nextcloud Files App, although we have many more users on Talk, and it is just a normal standard feature in all other messaging apps.

**Additional context**
Nope, just a simple request that I can't see documented anywhere else.

**Comment by SystemKeeper** [comment]
Hey @marcusquinn 
I agree on that. The current photo picker does not allow selection of multiple pictures. There have been some changes (I think it was with iOS 14) to allow multiselection, so it definitely makes sense to look into this.

Alternatively of course you can select multiple photos in the library and then use the Nextcloud Talk share extension.

**Comment by marcusquinn** [comment]
The workaround iOS is to go to the Photos/Files apps directly, multi-select there, and then Share > Nextcloud Talk > select channel.

So, there is a workaround, and it is possible, it is likely just a minor interface programming oversight — that could be a small setting change for a significant user experience win.

**Comment by SystemKeeper** [comment]
> The workaround iOS is to go to the Photos/Files apps directly, multi-select there, and then Share > Nextcloud Talk > select channel.

Exactly!



> So, there is a workaround, and it is possible, it is likely just a minor interface programming oversight — that could be a small setting change for a significant user experience win.

Not sure if it’s really just a minor thing, but overall yes, you’re right, it can be improved 😄

**Comment by ferbulous** [comment]
> The workaround iOS is to go to the Photos/Files apps directly, multi-select there, and then Share > Nextcloud Talk > select channel.
> 
> So, there is a workaround, and it is possible, it is likely just a minor interface programming oversight — that could be a small setting change for a significant user experience win.

Hi, when I did this for live photos
It only backups the photos only (not the separate mp4 from live photos)
I've already enabled 'live photos' in the settings, while this does work if I manually transfer from the nextcloud app but not from the photos/files app.
@SystemKeeper Is there another workaround for the live photos?

**Comment by SystemKeeper** [comment]
> I've already enabled 'live photos' in the settings

I think you’re talking about the Files app, right? Because Talk does not have this setting. In fact there is no support for Live photos at the moment in talk, so it will always upload the key picture.

**Comment by ferbulous** [comment]
> no support for Live photos at the moment in talk, so it will always upload the key picture.

I see, that’s unfortunate
Is there a way to select all in album?
I’m thinking of selecting a few photos, add in album and just select all at once before uploading.
But i can’t find this option in the ios app yet

**Comment by SystemKeeper** [comment]
I think your only chance at the moment is upload it via the files app and then select it in talk iOS.

**Comment by ferbulous** [comment]
> I think your only chance at the moment is upload it via the files app and then select it in talk iOS.

But that still doesn’t work with live photos, correct?
So i would still need manually select each one

**Comment by SystemKeeper** [comment]
No multiselect then, no. But you could share it from the files app directly to a room, maybe that works?

**Comment by ferbulous** [comment]
Just to clarify, is the files app referring to the ios file app or the ios nextcloud app.
I did try earlier by sharing the live photos to nextcloud talk room but it just get imported as photos only

i’ve also tried using photosync which does have multi select, but some of the exported live photos randomly gets corrupted.

**Comment by SystemKeeper** [comment]
I was talking about th nextcloud files app, as I thought you were refering to it with the live photos settings. So there should be 2 files then, an image and a video. So you can share the video if you want, but you won't be able to get that "native live photo feeling" in talk-ios.
We are working on multiselect at some point, but live photos is out of the scope of this issue.
