### ISSUE TITLE
i18n: "Vote" for the number two

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/spreed-ios#850]
The following text string should be separate for the number two. In other languages, "votes" is spelled differently for the number two.
Example:

> 1 głos
> 2 głosy
> 5 głosów

https://github.com/nextcloud/talk-ios/blob/2ca11316becc17b2bfeadb9bc233e7b7fdb22d08/NextcloudTalk/en.lproj/Localizable.strings#L1301

**Comment by meskobalazs** [comment]
Or better yet, the now separate „vote” and „votes” strings should use proper pluralization. Edit: though I see that might have some technical implications.

**Comment by Ivansss** [comment]
We will start using stringdict files for plurals. That will allow to support plurals in different languages.
You can track the progress in this PR https://github.com/nextcloud/talk-ios/pull/861

**Comment by Ivansss** [comment]
Hi @Valdnet :)
We already have created a new project in transifex for plurals:
https://www.transifex.com/nextcloud/nextcloud/talk-ios-plurals

**Comment by Valdnet** [comment]
@Ivansss Thanks :+1:.
