### ISSUE TITLE
⏳ Handle expiring messages

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed-ios#853]
Server ref https://github.com/nextcloud/spreed/issues/7359

Tasks:
- [ ] Make sure items are removed from the view when their message expiration is reached even when the user doesn't leave the conversation
- [ ] Make sure when entering a conversation we don't show messages that expired in the meantime
- [ ] Handle system message

Follow-up possible:
- [ ] Add an option to set the expiration with:
    - Off
    - 4 weeks
    - 1 week
    - 1 day
    - 8 hours
    - 1 hour

**Comment by SystemKeeper** [comment]
> * 5 minutes

According to https://github.com/nextcloud/spreed/pull/7653#issuecomment-1196344741 and https://github.com/nextcloud/spreed/issues/7359#issuecomment-1123400708 the minimum should be 1 hour, did that change?

**Comment by nickvergessen** [comment]
Hmm right, because the cron job runs in a 5min interval it could take 9 minutes... Let me talk with Marco and go with 30 mins or 1 hour as minimum

**Comment by nickvergessen** [comment]
1h minimum
