### ISSUE TITLE
No Audio/Video when using iPhone 11 with eSIM

### ISSUE THREAD

**Issue by SlenderF** [nextcloud/spreed-ios#860]
## Steps to reproduce
1. Use iPhone 11 (Client-A) to make a call to another iPhone (Client-B) or another one (Client-C)
2. Client-A(WiFi) <-> Client-B (WiFi or 4G/LTE) or Client-A(WiFi) <-> Client-C (WiFi or 4G/LTE) work fine.
3. Try to connect when Client-A is using mobile internet (4G/LTE). Then there is no Audio/Video.

### Expected behaviour
Audio and Video should work all the time regardless if Client-A is using 4G/LTE or Wi-Fi. 

### Actual behaviour
If Client-A is connected via 4G/LTE there is no Audio/Video regardlress of the connection type of Client-B or Client-C. Unless Client-A gets Wi-Fi calls are not working. 

STUN: using official Nextcloud's stun (stun.nextcloud.com:443) or a custom one doesn't make any difference.
TURN: coturn and eturnal

We tried Coturn latest release 4.5.2 (https://github.com/coturn/coturn) as well as Eturnal 1.10.1 (https://github.com/processone/eturnal) as a TURN. Tried to set `turn: only` and `turns: only`  as well as  `turn: and turns:` with (UDP and TCP, UDP only and TCP only) in the Nextcloud settings `/settings/admin/talk`. Tried with TURN being set up using standard ports `3478/5349` as well as just `443`. Tried Let's Encrypt and ZeroSSL for TLS on the TURN server. 

All the options we tried the tool from Nextcloud settings `/settings/admin/talk` always shows OK( a "tick" meaning that it can connect and receive ICE candidates from TURN).

We have several more iPhones (Client-B and Client-C) and all of them work fine Client-B <-> Client-C regardless of the network.
And only the iPhone 11 (Client-A) does not work on 4G/LTE. The only difference is that it has eSIM instead of a normal SIM-card and it is in the Roaming currently. It might be that it has something to do with a mobile carrier although Whatsapp, Telegram, Signal as well standard SIP via Zoiper work perfectly on this iPhone using 4G/LTE. 

I can debug Coturn (or eturnal) and see their logs on the server although it has not that much of information. Mainly the errors are:
> TCP socket closed remotely
> reason: TLS/TCP socket buffer operation error (callback) or  
> reason: TCP connection closed by client (callback) or  
> reason: allocation timeout

I'm not sure if TURN works correctly at all. Before we have never had any issues with audio/video connections. We've been using NextcloudTalk (with STUN and TURN) for a very long time and maybe wouldn't have even noticed the issue if not this iPhone 11. It seems there might be something that causes NextcloudTalk App (iOS) to close/interrrupt the TURN connection.

I tried to capture iOS console log using iMazing as desribed here (https://github.com/nextcloud/talk-ios/issues/851) but the log is too big and it's hard to understand what is going on on the client's side.

**Is there any other way to to check detailed logs of signalling of the server and iOS app? Maybe that would at least point out to an error somewhere.**

## Device information
**Device:** iPhone 11 Pro
**iOS version:** 15.6.1
**Talk version:** 14.0.3

## Server information
**Nextcloud version:** 24.0.4
**Talk version:** 14.0.4
**Custom Signaling server configured:** no
**Custom TURN server configured:** yes (tried Coturn and Eturnal)
**Custom STUN server configured:** yes (tried both stun.nextcloud.com:443 and Coturn or Eturnal)

### Server log (data/nextcloud.log)
<details>
I can upload fresh logs anytime if neccessary. Just not sure which logs to start with. Either Nextcloud Server or Coturn or iPhone console log. 

If there is any idea where to start from I will be ready to make fresh debugging and upload all the logs here.
</details>

**Comment by SystemKeeper** [comment]
Hey @SlenderF 
at first glance this does sound very much like a connectivity issue. I don't think the eSIM is an issue here, but roaming on a different carrier might be. If it's working on all other devices and also when the device has wifi connectivity, I don't think it's an issue with talk-ios per se. Is this connection made over the internet or is there a vpn involved or something?

Regarding the console log: iOS tends to log many things to the console, making debugging very hard. A few things you might want to try:
* Filter by the process name ("NextcloudTalk") and see if anything relevant stands out
* There are quite a few `NSLog`s in `NCPeerConnection` (see https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/NCPeerConnection.m), this might help to get an idea as to what you need to look for. If nothing sticks out, it might at least give you a clue at what timestamp to look for other events.

Other than that there's currently no way in talk-ios to debug this further.
You could try to use the web version of talk on the problematic iPhone to see, if a successful connection is possible this way, but it's not optimized for small screens like the iPhone (make sure you allow camera and microphone access in safari for that website).

**Comment by SystemKeeper** [comment]
Hey @SlenderF 
I'll close this issue. Feel free to let us know if you have any indication that this might indeed be a talk-ios issue.

**Comment by raudraido** [comment]
I want to add that I have a iphone11proMax and I do not hear nextcloud talk calls. They  hear me, but I have no sound. Also every other iphone which I have, works.
