### ISSUE TITLE
Improve Chat look in Talk IOS

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/spreed-ios#871]
Hi all what do you all think about impending a new chat look similar to the Talk Android or even the iMessage look

Talk Android Screenshot
![Screenshot_20220913-143330_Talk QA](https://user-images.githubusercontent.com/59488153/189993684-413b0db6-8e4e-4d4a-8f85-1fc7ff1c9a03.jpg)

**Comment by SystemKeeper** [comment]
Duplicate of https://github.com/nextcloud/talk-ios/issues/698
