### ISSUE TITLE
Ability to change time from 24 hour to 12 hour

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/spreed-ios#872]
Is there a way to change the time in the app from 24 hours to 12 hours? Maybe have the app detect that way its setup on the phone so then it can also show under the Talk app. as of right now it runs on 24 hour time. Most of users in the US run on 12 hour time and some people cant read 24 hour time.

**Comment by SystemKeeper** [comment]
Hey @andyxheli 
Thanks for mentioning this. Indeed we currently force 24h layout.

![image](https://user-images.githubusercontent.com/1580193/190225557-cc2362ea-52f1-4277-ad78-ff088365fe9c.png)


```diff
--- a/NextcloudTalk/NCUtils.m
+++ b/NextcloudTalk/NCUtils.m
@@ -179,7 +179,8 @@ + (NSString *)readableTimeOrDateFromDate:(NSDate *)date
 + (NSString *)getTimeFromDate:(NSDate *)date
 {
     NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
-    [formatter setDateFormat:@"HH:mm"];
+    [formatter setTimeStyle:NSDateFormatterShortStyle];
+    [formatter setDateStyle:NSDateFormatterNoStyle];
     return [formatter stringFromDate:date];
 }
```

@Ivansss Any reason for "HH:mm" in the first place? Or can we go with the patch above?

**Comment by AndyXheli** [comment]
Hi @SystemKeeper Youre welcome! Thank - you for looking into it

**Comment by Ivansss** [comment]
> Any reason for "HH:mm" in the first place? Or can we go with the patch above?

The main reason back then was that the dateLabel has a fixed width, so I decided to go with a fixed format.
I think it really makes sense to use the locale format and use the patch you wrote above, but we should also make the dataLabel witdh or its font size adjustable.
