### ISSUE TITLE
Save flash setting for camera attachment option

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#885]
**Is your feature request related to a problem? Please describe.**
Currently when I want to quickly send a picture, I tap the attachments clip icon and choose "Camera". This opens a camera view which always has the flash set to auto.

**Describe the solution you'd like**
It would be nice if the previous flash setting (on/off/auto) was remembered, for example I usually shoot without the flash and every time I forget that this app activates it so I have to re-take the picture after deactivating it.

**Describe alternatives you've considered**
Always remembering to manually turn off the flash, but it's more of an annoyance rather than an alternative.

**Additional context**
Flash settings in the camera view (after tapping on the flash icon at the top):
![](https://user-images.githubusercontent.com/48513706/192117936-14a4e10c-361a-40b9-9336-21bbf4a36d77.jpeg)

**Comment by SystemKeeper** [comment]
Makes sense.
For reference:
https://developer.apple.com/documentation/uikit/uiimagepickercontroller/1619124-cameraflashmode
https://github.com/nextcloud/talk-ios/blob/d9b9fc3203bf0c90ac960e73be8bfc5cea052814/NextcloudTalk/NCChatViewController.m#L1381-L1390

**Comment by Ivansss** [comment]
The flash setting will be saved in the next version :)
Thanks for reporting it @e-caste ;)

**Comment by e-caste** [comment]
Thank you! @Ivansss
