### ISSUE TITLE
Allow pasting images into text field

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#887]
**Is your feature request related to a problem? Please describe.**
Currently if I copy an image I can't paste it into the app's text field.

**Describe the solution you'd like**
It would be nice if we could do it, especially since on iOS 16 there's a new button to copy and delete a screenshot.

**Describe alternatives you've considered**
Currently the alternative is to save the image, then attach it from the camera roll.

**Additional context**
iOS 16 screenshot buttons after tapping "Done":
![image](https://user-images.githubusercontent.com/48513706/192163125-e52a2694-5437-41be-86d6-badb53ae336f.jpeg)

**Comment by SystemKeeper** [comment]
> **Describe alternatives you've considered** Currently the alternative is to save the image, then attach it from the camera roll.

You also can use the share button in the screenshot ui and share directly with talk 😄

**Comment by e-caste** [comment]
@SystemKeeper you're absolutely right. The screenshot example maybe isn't the best one, there are other instances where I'm on a website and I want to simply copy and paste an image to send it without saving it to the camera roll. I believe this is still a feature that can be added.

**Comment by SystemKeeper** [comment]
Sorry, I wasn't saying this is not something to consider, I was just pointing out the alternatives 😉 
On a more technical note I'm not sure it is worth the work as long as we're still using SlackTextViewController for the chat view, but we should keep it in mind.

**Comment by e-caste** [comment]
@SystemKeeper it looks like it supports pasting media into the TextView, if I'm not mistaken: https://github.com/Ivansss/SlackTextViewController/blob/890c29485e3eb04f8e00f6ed80096197ed162168/Source/SLKTextView.h#L64
And it should only be a matter of parameters passed at instantiation:
` _textView.pastableMediaTypes = SLKPastableMediaTypeAll;`  
to add here: https://github.com/Ivansss/SlackTextViewController/blob/890c29485e3eb04f8e00f6ed80096197ed162168/Source/SLKTextInputbar.m#L159

**Comment by SystemKeeper** [comment]
Honestly I don't think it's worth the work at the moment. As the SlackTextViewController has been deprecated for a while and we try to patch it so it's still working with the latest iOS versions, it's only a matter of time when it gets replaced (see #931). Also it would be nice to have this with #779 ... 
If you want to play around with it, you should be able to do this in https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/NCMessageTextView.m or https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/NCChatViewController.m, where the SLKTextView (NCMessageTextView in our case) is used.
