### ISSUE TITLE
Use dark mode avatars when dark mode is used.

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed-ios#941]
Android ref https://github.com/nextcloud/talk-android/issues/2409

So when darkmode is on, you should load the avatar with /dark appended to the URL:
https://github.com/nextcloud/server/pull/33752/files#diff-4498c88983ae18872bd47b365d72a3604d1850596ea052d36da8bb7ad28f207eR48

**Comment by SystemKeeper** [comment]
Currently the avatars are cached by the lib, need to make sure we invalidate the cache if the appearance changes

**Comment by nickvergessen** [comment]
or use 2 different cache keys.  `$userId` and `$userId/dark` since / can not appear in user ids

**Comment by SystemKeeper** [comment]
Yes, I’ll take a look. Might not be a problem afterall, because the url is the key 🧐

**Comment by Ivansss** [comment]
Since the urls are different there should not be an issue with the cache.
But we might need to refresh (e.g. RoomsTablewView) if there is an appearce change.

**Comment by SystemKeeper** [comment]
I don't see a capability or a backport - so we check for NC 25 when doing this?

**Comment by Ivansss** [comment]
> so we check for NC 25 when doing this?

Right! What would be the best way to proceed here @nickvergessen ?
I guess that's the only possible check we can do at the moment, right?

**Comment by nickvergessen** [comment]
Yeah, it's a server thing and server people are not used to capabilities (yet).
So yeah can you check the server version?

**Comment by SystemKeeper** [comment]
Yep, we store the server version already, so that should be pretty easy to do 👍
