### ISSUE TITLE
Very long load times for big folders when sending attachment from Nextcloud

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#946]
## Steps to reproduce
1. Open the app
2. Open a chat
3. Select attachments->Nextcloud
4. Choose a folder containing many files
5. Wait for ~1 minute

### Expected behaviour
Much quicker load of files present in big folder. For comparison, opening the same folder from the Nextcloud iOS app (4.5.3) takes around half a second to show some files.

### Actual behaviour
I have to wait an unfeasibly long amount of time, so long that, since I typically use the "send files from Nextcloud" button if I have already uploaded them (to the Talk folder), it's much quicker for me to resend them instead of selecting the same previously uploaded file from the Nextcloud Talk folder.

Size of folder: 254 items, 700 MB, all media.
Time on the same LAN of the server: ~40 seconds.  
Time on 4G: ~80 seconds.

## Device information

**Device:** iPhone X

**iOS version:** 16.0.3

**Talk version:** 15.0.0

## Server information

**Nextcloud version:** 25.0.0

**Talk version:** 15.0.0

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by SystemKeeper** [comment]
Hey @e-caste 
thank you for your report! I can confirm that depending on the size of the folder it might not be the fastest experience. Talk-ios does not cache any folder information, so each time you select "Send files from Nextcloud" the folder(s) are fetched directly from the server. In contrast the iOS Files app does cache the folder structure. Not sure if this can be improved on our side (we get the information from the ios-communications-lib), but just wanted to provide some background info.

**Comment by e-caste** [comment]
@SystemKeeper if you don't want to cache the directory structure info maybe you could speed up the request by asking for only part of the contents in multiple API calls while the user scrolls down? E.g. get the first 50 folder contents, then only if the user scrolls down (or in any case, to be prepared for a potential scrolldown) get the next 50, and so on.

Total request time is equal or slightly greater due to multiple requests but the time to user interaction is heavily reduced.

**Comment by SystemKeeper** [comment]
Hey @e-caste,

yea, I was thinking in a similar direction. I already did a test in only requesting the attributes we actually need and not the whole object:

```diff
--- a/NextcloudTalk/NCAPIController.m
+++ b/NextcloudTalk/NCAPIController.m
@@ -1790,8 +1790,21 @@ NSInteger const kReceivedChatMessagesLimit = 100;
 - (void)readFolderForAccount:(TalkAccount *)account atPath:(NSString *)path depth:(NSString *)depth withCompletionBlock:(ReadFolderCompletionBlock)block
 {
     [self setupNCCommunicationForAccount:account];
+
+    NSString *body = @"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\
+            <d:propfind xmlns:d=\"DAV:\" xmlns:oc=\"http://owncloud.org/ns\" xmlns:nc=\"http://nextcloud.org/ns\">\
+                <d:prop>\
+                    <d:getlastmodified />\
+                    <d:getcontenttype />\
+                    <d:resourcetype />\
+                    <fileid xmlns=\"http://owncloud.org/ns\"/>\
+                    <is-encrypted xmlns=\"http://nextcloud.org/ns\"/>\
+                    <has-preview xmlns=\"http://nextcloud.org/ns\"/>\
+                </d:prop>\
+            </d:propfind>";
+
     NSString *serverUrlString = [NSString stringWithFormat:@"%@%@/%@", account.server, [self filesPathForAccount:account], path ? path : @""];
-    [[NCCommunication shared] readFileOrFolderWithServerUrlFileName:serverUrlString depth:depth showHiddenFiles:NO requestBody:nil customUserAgent:nil addCustomHeaders:nil timeout:60 queue:dispatch_get_main_queue() completionHandler:^(NSString *accounts, NSArray<NCCommunicationFile *> *files, NSData *responseData, NSInteger errorCode, NSString *errorDescription) {
+    [[NCCommunication shared] readFileOrFolderWithServerUrlFileName:serverUrlString depth:depth showHiddenFiles:NO requestBody:[body dataUsingEncoding:NSUTF8StringEncoding] customUserAgent:nil addCustomHeaders:nil timeout:60 queue:dispatch_get_main_queue() completionHandler:^(NSString *accounts, NSArray<NCCommunicationFile *> *files, NSData *responseData, NSInteger errorCode, NSString *errorDescription) {
         if (errorCode == 0 && block) {
```

With the above change it's noticeably faster for me (time cut in half I would guess, so not perfect, but better). 
I didn't see support for paging, but that might be a limitation of the lib, not of the api.

**Comment by SystemKeeper** [comment]
Hey @e-caste since you now have a development setup running for talk-ios, could you try the proposed patch above and see if it helps reducing the time? Would be nice to know before I get that in 😄

**Comment by e-caste** [comment]
@SystemKeeper yes but not in the next few days, sorry
