### ISSUE TITLE
Change audio output when someone leaves a call (speaker to earpiece)

### ISSUE THREAD

**Issue by Yo-DDV** [nextcloud/spreed-ios#952]
## Steps to reproduce
1. 3 people are in the call ( A B C )
2. A left the call
3. Sound of the call switch to the earpiece located on the screen (for normal calls) + echo between b and c

### Expected behaviour
Call audio should continue to play through the phone's speaker

### Actual behaviour

the sound changes from the loudspeaker to the earpiece, also an audio echo appears between B and C. If A enters the call again then everything is working correctly again. The scenario also works with A - B - C - D => C stop de call => A - B - D echo + HP switch

## Device information

Iphone 13 pro max

**iOS version:** 10/…
16.0
**Talk version:** 11.1.1
15.0.0
## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`)
24.0.5
**Talk version:** (see apps admin page: `/index.php/settings/apps`)
14.0.5
**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/settings/admin/talk#signaling_server`)
yes
**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`)
yes
**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`)
yes
### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by TBI-NS** [comment]
<<bump>>
It's a problem that requires us to make our calls outside of talk ..

**Comment by TBI-NS** [comment]
The problem persists in version 15.1.1 (still no problem on the android apk and the pc version, it's only the iphone)

**Comment by SystemKeeper** [comment]
Hey @TBI-NS, there has been no changes in 15.1.1 regarding this.

**Comment by SystemKeeper** [comment]
Hey @TBI-NS We are trying to reproduce the issue. We saw that a few times, but not consistently. So I was wondering, is this something you observed before iOS 16 as well or did this maybe start after the upgrade to iOS 16?

**Comment by TBI-NS** [comment]
Hello =)

Unfortunately I have no back on this bug .. because I switched to ios / iphone recently. Do you need to do a test on my server? we can organize this if you want

**Comment by SystemKeeper** [comment]
I see, thanks! I'm not sure at the moment, I don't think it's dependent on the server (at least I'm thinking this at the moment). I'll let you know if we need this, thanks for the offer!

**Comment by TBI-NS** [comment]
I allow myself to bring up this bug which has completely prevented meeting on talk for months now.

As a reminder :

- Problem only on ios / iphone
- it appears when one of the conversation participants leaves the call.

Thank you for your work and happy new year to the team!

**Comment by SystemKeeper** [comment]
> I allow myself to bring up this bug which has completely prevented meeting on talk for months now.

Believe me when I say we already looked into this and invested quite some time and didn't find a solution. Luckily it looks like there's now a solution in #1036. This still needs review and testing, but if everything goes well, this issue might be solved.

**Comment by SystemKeeper** [comment]
Hey @TBI-NS we released 15.2.4 to TestFlight: https://testflight.apple.com/join/cxzyr1eO 
Would be cool if you could test it and report back if this solves your issue!

**Comment by TBI-NS** [comment]
Hello, here !

I'm doing the test on the testflight version and I confirm that the bug is solved, so you can put the fix in production =)

Thank you very much, lots of force to the whole team
