### ISSUE TITLE
The status bar disappears after tapping a Nextcloud Talk notification while being in another app

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#958]
## Steps to reproduce
1. Receive a Talk notification
2. Tap it, this opens the app in the right chat where the message of the notification was received
3. 🪄 the status bar is gone!

### Expected behaviour
The status bar is there as usual.

### Actual behaviour
Pouf! Also, the back button which is still showing does not work.
![image](https://user-images.githubusercontent.com/48513706/198147730-0578cb2f-b30f-4542-b398-b6916ddbc2cb.jpeg)

## Device information

**Device:** iPhone X

**iOS version:** 16.1

**Talk version:** 15.0.0

## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`) 25.0.0

**Talk version:** (see apps admin page: `/index.php/settings/apps`) 15.0.0

**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/settings/admin/talk#signaling_server`) no

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`) yes

**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`) yes

### Server log (data/nextcloud.log)
Not relevant.

**Comment by SystemKeeper** [comment]
Well, that shouldn't be the case 😅
Does it always happen or just sometimes?

**Comment by e-caste** [comment]
@SystemKeeper just sometimes, but it's happened to me at least twice since the last major. This time I managed to get it on camera. Btw the only way to "fix it" is to force close and reopen the app.

**Comment by SystemKeeper** [comment]
Can you please try the following?

* Be in chat A
* Move app to background
* (Maybe open another app)
* Receive a push from chat B
* Tap on that push

Is it now always reproducible ?

**Comment by e-caste** [comment]
@SystemKeeper tested and nope. Also, I was always in the same chat when that happened.

**Comment by SystemKeeper** [comment]
> @SystemKeeper tested and nope. Also, I was always in the same chat when that happened.

Okay, thanks for testing. I have a idea which might help, but not sure...
