### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL initFileURLWithPath:]: nil string parameter'

### ISSUE THREAD

**Issue by ridcridc1** [nextcloud/spreed-ios#972]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL initFileURLWithPath:]: nil string parameter'

**Comment by SystemKeeper** [comment]
Hey @ridcridc1 thanks for opening the issue. Please provide additional information on what happened, what you tried, etc. Just from this it's a bit hard to guess....

**Comment by ridcridc1** [comment]
When i run the app, it show the first screen, then a get the exception and the UI Hangs,

**Comment by ridcridc1** [comment]
<img width="483" alt="Screenshot 2022-11-07 at 11 04 03" src="https://user-images.githubusercontent.com/106596605/200258558-9b0839bc-ed27-4483-b733-3d97b93a94b9.png">

**Comment by SystemKeeper** [comment]
Please follow the steps at https://github.com/nextcloud/talk-ios#run-the-project
Mostlikley you did not set the app group identifier.

**Comment by ridcridc1** [comment]
Worked!! it is true i forgot to do so,Thanks so much
