### ISSUE TITLE
⏺️ Call recording support

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed-ios#977]
See meta issue in https://github.com/nextcloud/spreed/issues/8324

## Eta 23.11. #997 
- [x] Showing the system messages
- [x] Show "Recording icon" in the call view when the call is being recorded

**Comment by SystemKeeper** [comment]
> ## Eta 23.11.
> * [x]  Showing the system messages
> * [x]  Show "Recording icon" in the call view when the call is being recorded

So, quick update, this is done (except some small adjustments when the name of capability is defined). As this includes quite some changes to the call view, the PR will be done a bit later. Here's a screenshot of the current state:
<img width=250 src="https://user-images.githubusercontent.com/1580193/203585227-c4c30366-fc84-4a0a-bc2b-089280e51916.png" />

**Comment by nickvergessen** [comment]
Specs and api urls at

https://github.com/nextcloud/spreed/issues/8326

**Comment by SystemKeeper** [comment]
Perfect, thanks!
