### ISSUE TITLE
Scroll to selected message in chat after choosing a message from the search list

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#988]
**Is your feature request related to a problem? Please describe.**
When I search for a message and I find it, I'd like to be able to read it fully.

**Describe the solution you'd like**
1. search for a message
2. find the message
3. tap the message
4. the correct chat opens with that message in the view (this currently doesn't happen and the app simply opens the chat without scrolling up)

**Describe alternatives you've considered**
Scrolling up a lot after exercising for the finger marathon, trying to remember the message contents really hard, using the web version of Talk(?)

**Additional context**
🕵️

**Comment by SystemKeeper** [comment]
https://github.com/nextcloud/talk-ios/issues/891

and basically this https://github.com/nextcloud/spreed/issues/6046

Closing as duplicate :)

**Comment by e-caste** [comment]
Sorry, didn't see it

**Comment by SystemKeeper** [comment]
No problem 👍
