### ISSUE TITLE
Allow to manually sort the favorite chats

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#990]
**Is your feature request related to a problem? Please describe.**
Favorites are sorted based on last sent/received message.

**Describe the solution you'd like**
I'd like to be able to set the order manually.

**Describe alternatives you've considered**
N/A

**Additional context**
Some other apps do it and I like having that ability, so I can rely on the first chats always being sorted the same way.

**Comment by SystemKeeper** [comment]
Hey @e-caste thank you for the feature request. We discussed this internally and at the moment this is not something we want to do. The feature is build like this in the server and android client and changes are not planned at the moment.
