### ISSUE TITLE
Received messages have a mildly rough animation

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#992]
## Steps to reproduce
1. Have a chat open
2. Receive a message in the chat
3. Observe the messages slightly jump

### Expected behaviour
Smoother animation. I have observed rough/twitchy/jumpy animations in these situations:
- receiving a message with the chat open
- loading new messages / updating the chat after opening a chat (either sent from the current account from another device or received from other participants) - in this case the chat jumps down after having loaded all messages at the same time
- sometimes when opening a chat, there is no animation but the app glitches from the chat list view to the chat view directly

### Actual behaviour
The chat has a very small twitch, which can be annoying when receiving multiple messages.

## Device information

**Device:** iPhone X

**iOS version:** 16.1.1

**Talk version:** 15.1.1

## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`) 25.0.1

**Talk version:** (see apps admin page: `/index.php/settings/apps`) 15.0.1

**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/settings/admin/talk#signaling_server`) no

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`) yes

**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`) yes

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by SystemKeeper** [comment]
Hey @e-caste, there were some improvements in the latest TestFlight builds about this. Maybe you could take a look if it's working now better for you?

**Comment by e-caste** [comment]
@SystemKeeper Hi, sorry for the delay in the response. I have installed version 16.0.0 from the App Store which I believe includes these changes but I haven't noticed any difference, e.g. when I open a chat with new messages they appear all at once without animations.

**Comment by SystemKeeper** [comment]
Thanks for the info! Maybe I'm misunderstand here, but if you open a chat with unread messages, then yes, there's no animation to expect there.  At least this is how it is at the moment. Might take a look if that could be improved, but I think it will not work smoothly with the unread marker..

**Comment by e-caste** [comment]
@SystemKeeper I see. Then in that case:
- the missing animation when entering a chat appears to be solved
- the lack of animation when opening a chat with unread messages is expected behaviour, but it would be nice to have the messages scrolling up from the bottom of the chat, since now it looks like a bug (even though it's not) and reading new messages is a very common use of a chat app
- the scrolling animation on receiving a new message while being in the chat that receives it seems to be working, though I have noticed that the scrolling does not take into consideration the "Today" tag if the message is the first of the day (meaning it doesn't scroll down enough)
