### ISSUE TITLE
Attachment from Nextcloud shows empty selection/navigation box saying "no files available" / in original: "keine Dateien vorhanden"

### ISSUE THREAD

**Issue by freundhein** [nextcloud/spreed-ios#996]
## Steps to reproduce
1. enter a chat
2. select attachments
3. select Nextcloud
4. this opens an empty box including neither folders nor files, only exit via cancel is possible

### Expected behaviour
under above point 4 I would expect folders and files to show up for navigation and selection 

### Actual behaviour
after executing step 3 an exmpty box shows up, in the headline a home icon, left to cancel, right to choose sorting,
a faint icon in the box just tells "keine Dateien vorhanden" / "no files found"

## Device information

**Device:** iPhone 11

**iOS version:** 16.1.1 (issue was the same on latest 15.?.? version)

**Talk version:** 15.1.1

## Server information

**Nextcloud version:** 24.0.7

**Talk version:** 14.0.6

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

### Server log (data/nextcloud.log)
causing no log messages on server side

**Comment by SystemKeeper** [comment]
Hey @freundhein hm, this should work™.
Anything special about your root folder? How many files and folders are in your root?
Does the Files app work for you?

**Comment by freundhein** [comment]
my root folder includes 10 subfolders, and 0 (zero) files
3 of those folders are group folders
yes, the files app works perfectly showing all subfolders

BTW: same setup on my Android tablet works just fine.

**Comment by freundhein** [comment]
hint: I just added now a plain test.md file with some dummy content to the root folder
but resulting in no change for Talk App, i.e. still showing "no files available"

**Comment by SystemKeeper** [comment]
Would it be possible for you to create a new test user and try with this user? So we can check if it’s user or instance dependant?!

**Comment by freundhein** [comment]
sure, done.
I created a plain test user, who just got the default folders and files populated. This user is not assigned to any of the groups which my standard account is assigned to, likewise my standard group folders are not mapped to it, too.

Result: unfortunately no change from iOS App's perspective, i.e. when trying to share Nextcloud content form this new test account then just an empty box opens

**Comment by SystemKeeper** [comment]
> Result: unfortunately no change from iOS App's perspective, i.e. when trying to share Nextcloud content form this new test account then just an empty box opens

Okay, then we can rule out group folders and it might be something else going on here. Would you be able to share the test account with me so I we can take a look? You can send it to the mail found in this file on the top: https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/CallsFromOldAccountViewController.swift

**Comment by SystemKeeper** [comment]
So the problem boils down to nextcloud being installed in a sub-directory on the server, e.g. `https://mydomain.com/nextcloud/`. In this case the properties in `getItemsInDirectory` in `DirectoryTableViewController` look like this:

```
(lldb) po item.path
/nextcloud/remote.php/dav/files/test/

(lldb) po _userHomePath
/remote.php/dav/files/test

(lldb) po itemPath
/nextcloud/
``` 

so the subdirectory gets part of `itemPath` and therefore the check if we're in the correct directory fails.
I suspect that this was introduced when switching from WebDAV to DAV in #864.

We could do something like this to make sure we always get the "correct last path": 

```diff
diff --git a/NextcloudTalk/DirectoryTableViewController.m b/NextcloudTalk/DirectoryTableViewController.m
index 419adefa..ffed1661 100644
--- a/NextcloudTalk/DirectoryTableViewController.m
+++ b/NextcloudTalk/DirectoryTableViewController.m
@@ -169,6 +169,12 @@
             for (NKFile *item in items) {
                 NSString *currentDirectory = [self->_path isEqualToString:@""] ? @"/" : [self->_path lastPathComponent];
                 NSString *itemPath = [item.path stringByReplacingOccurrencesOfString:self->_userHomePath withString:@""];
+
+                NSArray *itemPathParts = [item.path componentsSeparatedByString:self->_userHomePath];
+                if (itemPathParts.count > 1) {
+                    itemPath = itemPathParts[1];
+                }
+
                 if ([[itemPath lastPathComponent] isEqualToString:currentDirectory] && !item.e2eEncrypted) {
                     [itemsInDirectory addObject:item];
                 }
```

Thanks for the help @freundhein !

**Comment by SystemKeeper** [comment]
Hey @freundhein 
15.2 Beta was released to TestFlight, if you want to test it: https://testflight.apple.com/join/cxzyr1eO

**Comment by freundhein** [comment]
works now :+1:

**Comment by SystemKeeper** [comment]
Thank you for testing! 👍
